/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PascalitoGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Programa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentEStringParserRuleCall_1_0 = (RuleCall)cIdentAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBlocoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBlocoBlocoParserRuleCall_3_0 = (RuleCall)cBlocoAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Programa:
		//	'programa' Ident=EString
		//	'{'
		//	bloco=Bloco
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'programa' Ident=EString '{' bloco=Bloco '}'
		public Group getGroup() { return cGroup; }
		
		//'programa'
		public Keyword getProgramaKeyword_0() { return cProgramaKeyword_0; }
		
		//Ident=EString
		public Assignment getIdentAssignment_1() { return cIdentAssignment_1; }
		
		//EString
		public RuleCall getIdentEStringParserRuleCall_1_0() { return cIdentEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//bloco=Bloco
		public Assignment getBlocoAssignment_3() { return cBlocoAssignment_3; }
		
		//Bloco
		public RuleCall getBlocoBlocoParserRuleCall_3_0() { return cBlocoBlocoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ComandoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Comando");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallProcedimentoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAtribuicaoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDesvioParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLoopParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Comando:
		//	CallProcedimento | Atribuicao | Desvio | Loop;
		@Override public ParserRule getRule() { return rule; }
		
		//CallProcedimento | Atribuicao | Desvio | Loop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallProcedimento
		public RuleCall getCallProcedimentoParserRuleCall_0() { return cCallProcedimentoParserRuleCall_0; }
		
		//Atribuicao
		public RuleCall getAtribuicaoParserRuleCall_1() { return cAtribuicaoParserRuleCall_1; }
		
		//Desvio
		public RuleCall getDesvioParserRuleCall_2() { return cDesvioParserRuleCall_2; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_3() { return cLoopParserRuleCall_3; }
	}
	public class ExpressaoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Expressao");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallVariavelParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCallProcParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNumberParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cExpBinLogicaParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cExpBinParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cExpNegParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Expressao:
		//	CallVariavel | CallProc | Number | ExpBinLogica | ExpBin | ExpNeg;
		@Override public ParserRule getRule() { return rule; }
		
		//CallVariavel | CallProc | Number | ExpBinLogica | ExpBin | ExpNeg
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallVariavel
		public RuleCall getCallVariavelParserRuleCall_0() { return cCallVariavelParserRuleCall_0; }
		
		//CallProc
		public RuleCall getCallProcParserRuleCall_1() { return cCallProcParserRuleCall_1; }
		
		//Number
		public RuleCall getNumberParserRuleCall_2() { return cNumberParserRuleCall_2; }
		
		//ExpBinLogica
		public RuleCall getExpBinLogicaParserRuleCall_3() { return cExpBinLogicaParserRuleCall_3; }
		
		//ExpBin
		public RuleCall getExpBinParserRuleCall_4() { return cExpBinParserRuleCall_4; }
		
		//ExpNeg
		public RuleCall getExpNegParserRuleCall_5() { return cExpNegParserRuleCall_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BlocoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Bloco");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlocoAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVarKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDefvariavelAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDefvariavelVariavelParserRuleCall_1_1_0 = (RuleCall)cDefvariavelAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cDefvariavelAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cDefvariavelVariavelParserRuleCall_1_2_1_0 = (RuleCall)cDefvariavelAssignment_1_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cProcedimentoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDefprocedimentoAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDefprocedimentoProcedimentoParserRuleCall_2_1_0 = (RuleCall)cDefprocedimentoAssignment_2_1.eContents().get(0);
		private final Keyword cInicioKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExecutaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExecutaComandoParserRuleCall_4_0 = (RuleCall)cExecutaAssignment_4.eContents().get(0);
		private final Keyword cFimKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Bloco:
		//	{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento'
		//	defprocedimento+=Procedimento)*
		//	'Inicio' executa+=Comando* 'Fim';
		@Override public ParserRule getRule() { return rule; }
		
		//{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento' defprocedimento+=Procedimento)*
		//'Inicio' executa+=Comando* 'Fim'
		public Group getGroup() { return cGroup; }
		
		//{Bloco}
		public Action getBlocoAction_0() { return cBlocoAction_0; }
		
		//('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")*
		public Group getGroup_1() { return cGroup_1; }
		
		//'var'
		public Keyword getVarKeyword_1_0() { return cVarKeyword_1_0; }
		
		//defvariavel+=Variavel
		public Assignment getDefvariavelAssignment_1_1() { return cDefvariavelAssignment_1_1; }
		
		//Variavel
		public RuleCall getDefvariavelVariavelParserRuleCall_1_1_0() { return cDefvariavelVariavelParserRuleCall_1_1_0; }
		
		//("," defvariavel+=Variavel)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//defvariavel+=Variavel
		public Assignment getDefvariavelAssignment_1_2_1() { return cDefvariavelAssignment_1_2_1; }
		
		//Variavel
		public RuleCall getDefvariavelVariavelParserRuleCall_1_2_1_0() { return cDefvariavelVariavelParserRuleCall_1_2_1_0; }
		
		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
		
		//('procedimento' defprocedimento+=Procedimento)*
		public Group getGroup_2() { return cGroup_2; }
		
		//'procedimento'
		public Keyword getProcedimentoKeyword_2_0() { return cProcedimentoKeyword_2_0; }
		
		//defprocedimento+=Procedimento
		public Assignment getDefprocedimentoAssignment_2_1() { return cDefprocedimentoAssignment_2_1; }
		
		//Procedimento
		public RuleCall getDefprocedimentoProcedimentoParserRuleCall_2_1_0() { return cDefprocedimentoProcedimentoParserRuleCall_2_1_0; }
		
		//'Inicio'
		public Keyword getInicioKeyword_3() { return cInicioKeyword_3; }
		
		//executa+=Comando*
		public Assignment getExecutaAssignment_4() { return cExecutaAssignment_4; }
		
		//Comando
		public RuleCall getExecutaComandoParserRuleCall_4_0() { return cExecutaComandoParserRuleCall_4_0; }
		
		//'Fim'
		public Keyword getFimKeyword_5() { return cFimKeyword_5; }
	}
	public class VariavelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Variavel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariavelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Variavel:
		//	{Variavel} name=ID
		//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variavel} name=ID
		public Group getGroup() { return cGroup; }
		
		//{Variavel}
		public Action getVariavelAction_0() { return cVariavelAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class ProcedimentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Procedimento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Assignment cParametroAssignment_0_2_0 = (Assignment)cGroup_0_2.eContents().get(0);
		private final RuleCall cParametroVariavelParserRuleCall_0_2_0_0 = (RuleCall)cParametroAssignment_0_2_0.eContents().get(0);
		private final Group cGroup_0_2_1 = (Group)cGroup_0_2.eContents().get(1);
		private final Keyword cCommaKeyword_0_2_1_0 = (Keyword)cGroup_0_2_1.eContents().get(0);
		private final Assignment cParametroAssignment_0_2_1_1 = (Assignment)cGroup_0_2_1.eContents().get(1);
		private final RuleCall cParametroVariavelParserRuleCall_0_2_1_1_0 = (RuleCall)cParametroAssignment_0_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBlocoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBlocoBlocoParserRuleCall_2_0 = (RuleCall)cBlocoAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Procedimento:
		//	(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
		//	"{"
		//	bloco=Bloco
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")") "{" bloco=Bloco "}"
		public Group getGroup() { return cGroup; }
		
		//(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
		public Group getGroup_0() { return cGroup_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0_0() { return cNameIDTerminalRuleCall_0_0_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//(parametro+=Variavel ("," parametro+=Variavel)*)?
		public Group getGroup_0_2() { return cGroup_0_2; }
		
		//parametro+=Variavel
		public Assignment getParametroAssignment_0_2_0() { return cParametroAssignment_0_2_0; }
		
		//Variavel
		public RuleCall getParametroVariavelParserRuleCall_0_2_0_0() { return cParametroVariavelParserRuleCall_0_2_0_0; }
		
		//("," parametro+=Variavel)*
		public Group getGroup_0_2_1() { return cGroup_0_2_1; }
		
		//","
		public Keyword getCommaKeyword_0_2_1_0() { return cCommaKeyword_0_2_1_0; }
		
		//parametro+=Variavel
		public Assignment getParametroAssignment_0_2_1_1() { return cParametroAssignment_0_2_1_1; }
		
		//Variavel
		public RuleCall getParametroVariavelParserRuleCall_0_2_1_1_0() { return cParametroVariavelParserRuleCall_0_2_1_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//bloco=Bloco
		public Assignment getBlocoAssignment_2() { return cBlocoAssignment_2; }
		
		//Bloco
		public RuleCall getBlocoBlocoParserRuleCall_2_0() { return cBlocoBlocoParserRuleCall_2_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class CallProcedimentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProcedimento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDefinidoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cDefinidoProcedimentoCrossReference_0_0 = (CrossReference)cDefinidoAssignment_0.eContents().get(0);
		private final RuleCall cDefinidoProcedimentoIDTerminalRuleCall_0_0_1 = (RuleCall)cDefinidoProcedimentoCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParametroAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_0_0 = (RuleCall)cParametroAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParametroAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_1_1_0 = (RuleCall)cParametroAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//CallProcedimento:
		//	definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')') ';'
		public Group getGroup() { return cGroup; }
		
		//definido=[Procedimento]
		public Assignment getDefinidoAssignment_0() { return cDefinidoAssignment_0; }
		
		//[Procedimento]
		public CrossReference getDefinidoProcedimentoCrossReference_0_0() { return cDefinidoProcedimentoCrossReference_0_0; }
		
		//ID
		public RuleCall getDefinidoProcedimentoIDTerminalRuleCall_0_0_1() { return cDefinidoProcedimentoIDTerminalRuleCall_0_0_1; }
		
		//('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parametro+=Expressao ("," parametro+=Expressao)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_0() { return cParametroAssignment_1_1_0; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_0_0() { return cParametroExpressaoParserRuleCall_1_1_0_0; }
		
		//("," parametro+=Expressao)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_1_1() { return cParametroAssignment_1_1_1_1; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_1_1_0() { return cParametroExpressaoParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class AtribuicaoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Atribuicao");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAtribuiAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAtribuiVariavelCrossReference_0_0 = (CrossReference)cAtribuiAssignment_0.eContents().get(0);
		private final RuleCall cAtribuiVariavelIDTerminalRuleCall_0_0_1 = (RuleCall)cAtribuiVariavelCrossReference_0_0.eContents().get(1);
		private final RuleCall cOT_ASSIGNMENTParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cAtribuiResultadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAtribuiResultadoExpressaoParserRuleCall_2_0 = (RuleCall)cAtribuiResultadoAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Atribuicao:
		//	atribui=[Variavel] OT_ASSIGNMENT atribuiResultado=Expressao ';';
		@Override public ParserRule getRule() { return rule; }
		
		//atribui=[Variavel] OT_ASSIGNMENT atribuiResultado=Expressao ';'
		public Group getGroup() { return cGroup; }
		
		//atribui=[Variavel]
		public Assignment getAtribuiAssignment_0() { return cAtribuiAssignment_0; }
		
		//[Variavel]
		public CrossReference getAtribuiVariavelCrossReference_0_0() { return cAtribuiVariavelCrossReference_0_0; }
		
		//ID
		public RuleCall getAtribuiVariavelIDTerminalRuleCall_0_0_1() { return cAtribuiVariavelIDTerminalRuleCall_0_0_1; }
		
		//OT_ASSIGNMENT
		public RuleCall getOT_ASSIGNMENTParserRuleCall_1() { return cOT_ASSIGNMENTParserRuleCall_1; }
		
		//atribuiResultado=Expressao
		public Assignment getAtribuiResultadoAssignment_2() { return cAtribuiResultadoAssignment_2; }
		
		//Expressao
		public RuleCall getAtribuiResultadoExpressaoParserRuleCall_2_0() { return cAtribuiResultadoExpressaoParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class DesvioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Desvio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSeExpressaoParserRuleCall_2_0 = (RuleCall)cSeAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFacaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFacaComandoParserRuleCall_5_0 = (RuleCall)cFacaAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cElseKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cSeNaoAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cSeNaoComandoParserRuleCall_7_2_0 = (RuleCall)cSeNaoAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//Desvio:
		//	'if' '(' se=Expressao ')'
		//	'{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'if' '(' se=Expressao ')' '{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?
		public Group getGroup() { return cGroup; }
		
		//'if'
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//se=Expressao
		public Assignment getSeAssignment_2() { return cSeAssignment_2; }
		
		//Expressao
		public RuleCall getSeExpressaoParserRuleCall_2_0() { return cSeExpressaoParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//faca+=Comando*
		public Assignment getFacaAssignment_5() { return cFacaAssignment_5; }
		
		//Comando
		public RuleCall getFacaComandoParserRuleCall_5_0() { return cFacaComandoParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//('else' '{' seNao+=Comando* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'else'
		public Keyword getElseKeyword_7_0() { return cElseKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//seNao+=Comando*
		public Assignment getSeNaoAssignment_7_2() { return cSeNaoAssignment_7_2; }
		
		//Comando
		public RuleCall getSeNaoComandoParserRuleCall_7_2_0() { return cSeNaoComandoParserRuleCall_7_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSeExpressaoParserRuleCall_2_0 = (RuleCall)cSeAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFacaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFacaComandoParserRuleCall_5_0 = (RuleCall)cFacaAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loop:
		//	'Loop' '(' se=Expressao ')'
		//	'{' faca+=Comando* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loop' '(' se=Expressao ')' '{' faca+=Comando* '}'
		public Group getGroup() { return cGroup; }
		
		//'Loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//se=Expressao
		public Assignment getSeAssignment_2() { return cSeAssignment_2; }
		
		//Expressao
		public RuleCall getSeExpressaoParserRuleCall_2_0() { return cSeExpressaoParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//faca+=Comando*
		public Assignment getFacaAssignment_5() { return cFacaAssignment_5; }
		
		//Comando
		public RuleCall getFacaComandoParserRuleCall_5_0() { return cFacaComandoParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EBigDecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBigDecimal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//EBigDecimal ecore::EBigDecimal:
		//	INT? '.' INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT? '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class CallProcElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRepresentaProcAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRepresentaProcProcedimentoCrossReference_0_0 = (CrossReference)cRepresentaProcAssignment_0.eContents().get(0);
		private final RuleCall cRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1 = (RuleCall)cRepresentaProcProcedimentoCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParametroAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_0_0 = (RuleCall)cParametroAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParametroAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_1_1_0 = (RuleCall)cParametroAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//CallProc:
		//	representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')');
		@Override public ParserRule getRule() { return rule; }
		
		//representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup() { return cGroup; }
		
		//representaProc=[Procedimento]
		public Assignment getRepresentaProcAssignment_0() { return cRepresentaProcAssignment_0; }
		
		//[Procedimento]
		public CrossReference getRepresentaProcProcedimentoCrossReference_0_0() { return cRepresentaProcProcedimentoCrossReference_0_0; }
		
		//ID
		public RuleCall getRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1() { return cRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1; }
		
		//('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parametro+=Expressao ("," parametro+=Expressao)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_0() { return cParametroAssignment_1_1_0; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_0_0() { return cParametroExpressaoParserRuleCall_1_1_0_0; }
		
		//("," parametro+=Expressao)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_1_1() { return cParametroAssignment_1_1_1_1; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_1_1_0() { return cParametroExpressaoParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class CallVariavelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallVariavel");
		private final Assignment cRepresentaAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cRepresentaVariavelCrossReference_0 = (CrossReference)cRepresentaAssignment.eContents().get(0);
		private final RuleCall cRepresentaVariavelIDTerminalRuleCall_0_1 = (RuleCall)cRepresentaVariavelCrossReference_0.eContents().get(1);
		
		//CallVariavel:
		//	representa=[Variavel];
		@Override public ParserRule getRule() { return rule; }
		
		//representa=[Variavel]
		public Assignment getRepresentaAssignment() { return cRepresentaAssignment; }
		
		//[Variavel]
		public CrossReference getRepresentaVariavelCrossReference_0() { return cRepresentaVariavelCrossReference_0; }
		
		//ID
		public RuleCall getRepresentaVariavelIDTerminalRuleCall_0_1() { return cRepresentaVariavelIDTerminalRuleCall_0_1; }
	}
	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Number");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValorEIntParserRuleCall_1_0 = (RuleCall)cValorAssignment_1.eContents().get(0);
		
		//Number:
		//	{Number} Valor=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//{Number} Valor=EInt
		public Group getGroup() { return cGroup; }
		
		//{Number}
		public Action getNumberAction_0() { return cNumberAction_0; }
		
		//Valor=EInt
		public Assignment getValorAssignment_1() { return cValorAssignment_1; }
		
		//EInt
		public RuleCall getValorEIntParserRuleCall_1_0() { return cValorEIntParserRuleCall_1_0; }
	}
	public class ExpBinLogicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBinLogica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComutativaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cComutativaComutativaKeyword_0_0 = (Keyword)cComutativaAssignment_0.eContents().get(0);
		private final Keyword cExpBinLogicaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPrioridadeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPrioridadeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPrioridadeEBigDecimalParserRuleCall_3_1_0 = (RuleCall)cPrioridadeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperadorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOperadorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOperadorEStringParserRuleCall_4_1_0 = (RuleCall)cOperadorAssignment_4_1.eContents().get(0);
		private final Keyword cOperandoEsqKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOperandoEsqAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOperandoEsqExpressaoParserRuleCall_6_0 = (RuleCall)cOperandoEsqAssignment_6.eContents().get(0);
		private final Keyword cOperandoDirKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cOperandoDirAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cOperandoDirExpressaoParserRuleCall_8_0 = (RuleCall)cOperandoDirAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ExpBinLogica:
		//	Comutativa?='Comutativa'?
		//	'ExpBinLogica'
		//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
		//	'operandoEsq' operandoEsq=Expressao
		//	'operandoDir' operandoDir=Expressao
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//Comutativa?='Comutativa'? 'ExpBinLogica' '{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
		//'operandoEsq' operandoEsq=Expressao 'operandoDir' operandoDir=Expressao '}'
		public Group getGroup() { return cGroup; }
		
		//Comutativa?='Comutativa'?
		public Assignment getComutativaAssignment_0() { return cComutativaAssignment_0; }
		
		//'Comutativa'
		public Keyword getComutativaComutativaKeyword_0_0() { return cComutativaComutativaKeyword_0_0; }
		
		//'ExpBinLogica'
		public Keyword getExpBinLogicaKeyword_1() { return cExpBinLogicaKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('Prioridade' Prioridade=EBigDecimal)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Prioridade'
		public Keyword getPrioridadeKeyword_3_0() { return cPrioridadeKeyword_3_0; }
		
		//Prioridade=EBigDecimal
		public Assignment getPrioridadeAssignment_3_1() { return cPrioridadeAssignment_3_1; }
		
		//EBigDecimal
		public RuleCall getPrioridadeEBigDecimalParserRuleCall_3_1_0() { return cPrioridadeEBigDecimalParserRuleCall_3_1_0; }
		
		//('Operador' Operador=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Operador'
		public Keyword getOperadorKeyword_4_0() { return cOperadorKeyword_4_0; }
		
		//Operador=EString
		public Assignment getOperadorAssignment_4_1() { return cOperadorAssignment_4_1; }
		
		//EString
		public RuleCall getOperadorEStringParserRuleCall_4_1_0() { return cOperadorEStringParserRuleCall_4_1_0; }
		
		//'operandoEsq'
		public Keyword getOperandoEsqKeyword_5() { return cOperandoEsqKeyword_5; }
		
		//operandoEsq=Expressao
		public Assignment getOperandoEsqAssignment_6() { return cOperandoEsqAssignment_6; }
		
		//Expressao
		public RuleCall getOperandoEsqExpressaoParserRuleCall_6_0() { return cOperandoEsqExpressaoParserRuleCall_6_0; }
		
		//'operandoDir'
		public Keyword getOperandoDirKeyword_7() { return cOperandoDirKeyword_7; }
		
		//operandoDir=Expressao
		public Assignment getOperandoDirAssignment_8() { return cOperandoDirAssignment_8; }
		
		//Expressao
		public RuleCall getOperandoDirExpressaoParserRuleCall_8_0() { return cOperandoDirExpressaoParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ExpBinElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cComutativaAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cComutativaComutativaKeyword_0_0 = (Keyword)cComutativaAssignment_0.eContents().get(0);
		private final Keyword cExpBinKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPrioridadeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cPrioridadeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cPrioridadeEBigDecimalParserRuleCall_3_1_0 = (RuleCall)cPrioridadeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperadorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOperadorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOperadorEStringParserRuleCall_4_1_0 = (RuleCall)cOperadorAssignment_4_1.eContents().get(0);
		private final Keyword cOperandoDirKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cOperandoDirAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOperandoDirExpressaoParserRuleCall_6_0 = (RuleCall)cOperandoDirAssignment_6.eContents().get(0);
		private final Keyword cOperandoEsqKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cOperandoEsqAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cOperandoEsqExpressaoParserRuleCall_8_0 = (RuleCall)cOperandoEsqAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ExpBin:
		//	Comutativa?='Comutativa'?
		//	'ExpBin'
		//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
		//	'operandoDir' operandoDir=Expressao
		//	'operandoEsq' operandoEsq=Expressao
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//Comutativa?='Comutativa'? 'ExpBin' '{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
		//'operandoDir' operandoDir=Expressao 'operandoEsq' operandoEsq=Expressao '}'
		public Group getGroup() { return cGroup; }
		
		//Comutativa?='Comutativa'?
		public Assignment getComutativaAssignment_0() { return cComutativaAssignment_0; }
		
		//'Comutativa'
		public Keyword getComutativaComutativaKeyword_0_0() { return cComutativaComutativaKeyword_0_0; }
		
		//'ExpBin'
		public Keyword getExpBinKeyword_1() { return cExpBinKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('Prioridade' Prioridade=EBigDecimal)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Prioridade'
		public Keyword getPrioridadeKeyword_3_0() { return cPrioridadeKeyword_3_0; }
		
		//Prioridade=EBigDecimal
		public Assignment getPrioridadeAssignment_3_1() { return cPrioridadeAssignment_3_1; }
		
		//EBigDecimal
		public RuleCall getPrioridadeEBigDecimalParserRuleCall_3_1_0() { return cPrioridadeEBigDecimalParserRuleCall_3_1_0; }
		
		//('Operador' Operador=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'Operador'
		public Keyword getOperadorKeyword_4_0() { return cOperadorKeyword_4_0; }
		
		//Operador=EString
		public Assignment getOperadorAssignment_4_1() { return cOperadorAssignment_4_1; }
		
		//EString
		public RuleCall getOperadorEStringParserRuleCall_4_1_0() { return cOperadorEStringParserRuleCall_4_1_0; }
		
		//'operandoDir'
		public Keyword getOperandoDirKeyword_5() { return cOperandoDirKeyword_5; }
		
		//operandoDir=Expressao
		public Assignment getOperandoDirAssignment_6() { return cOperandoDirAssignment_6; }
		
		//Expressao
		public RuleCall getOperandoDirExpressaoParserRuleCall_6_0() { return cOperandoDirExpressaoParserRuleCall_6_0; }
		
		//'operandoEsq'
		public Keyword getOperandoEsqKeyword_7() { return cOperandoEsqKeyword_7; }
		
		//operandoEsq=Expressao
		public Assignment getOperandoEsqAssignment_8() { return cOperandoEsqAssignment_8; }
		
		//Expressao
		public RuleCall getOperandoEsqExpressaoParserRuleCall_8_0() { return cOperandoEsqExpressaoParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class OT_COMPARISONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OT_COMPARISON");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEqualsSignLessThanSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cEqualsSignEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		////terminal 
		//OT_COMPARISON:
		//	'<' | '>' | '=<' | '>=' | '==';
		@Override public ParserRule getRule() { return rule; }
		
		//'<' | '>' | '=<' | '>=' | '=='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'<'
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1() { return cGreaterThanSignKeyword_1; }
		
		//'=<'
		public Keyword getEqualsSignLessThanSignKeyword_2() { return cEqualsSignLessThanSignKeyword_2; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_3() { return cGreaterThanSignEqualsSignKeyword_3; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_4() { return cEqualsSignEqualsSignKeyword_4; }
	}
	public class OT_ARITHMETICElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OT_ARITHMETIC");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cPlusSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		
		////terminal 
		//OT_ARITHMETIC:
		//	'-' | '+' | '*' | '/';
		@Override public ParserRule getRule() { return rule; }
		
		//'-' | '+' | '*' | '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1() { return cPlusSignKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
	}
	public class OT_ASSIGNMENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OT_ASSIGNMENT");
		private final Keyword cHyphenMinusGreaterThanSignKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OT_ASSIGNMENT:
		//	'->';
		@Override public ParserRule getRule() { return rule; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword() { return cHyphenMinusGreaterThanSignKeyword; }
	}
	public class OT_NEGATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OT_NEGATE");
		private final Keyword cHyphenMinusKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OT_NEGATE:
		//	'-';
		@Override public ParserRule getRule() { return rule; }
		
		//'-'
		public Keyword getHyphenMinusKeyword() { return cHyphenMinusKeyword; }
	}
	public class ExpNegElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpNeg");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpNegKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPrioridadeKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPrioridadeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPrioridadeEBigDecimalParserRuleCall_2_1_0 = (RuleCall)cPrioridadeAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cOperadorKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cOperadorAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cOperadorEStringParserRuleCall_3_1_0 = (RuleCall)cOperadorAssignment_3_1.eContents().get(0);
		private final Keyword cNegaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNegaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNegaExpressaoParserRuleCall_5_0 = (RuleCall)cNegaAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ExpNeg:
		//	'ExpNeg'
		//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
		//	'nega' nega=Expressao
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ExpNeg' '{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)? 'nega' nega=Expressao '}'
		public Group getGroup() { return cGroup; }
		
		//'ExpNeg'
		public Keyword getExpNegKeyword_0() { return cExpNegKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('Prioridade' Prioridade=EBigDecimal)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Prioridade'
		public Keyword getPrioridadeKeyword_2_0() { return cPrioridadeKeyword_2_0; }
		
		//Prioridade=EBigDecimal
		public Assignment getPrioridadeAssignment_2_1() { return cPrioridadeAssignment_2_1; }
		
		//EBigDecimal
		public RuleCall getPrioridadeEBigDecimalParserRuleCall_2_1_0() { return cPrioridadeEBigDecimalParserRuleCall_2_1_0; }
		
		//('Operador' Operador=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Operador'
		public Keyword getOperadorKeyword_3_0() { return cOperadorKeyword_3_0; }
		
		//Operador=EString
		public Assignment getOperadorAssignment_3_1() { return cOperadorAssignment_3_1; }
		
		//EString
		public RuleCall getOperadorEStringParserRuleCall_3_1_0() { return cOperadorEStringParserRuleCall_3_1_0; }
		
		//'nega'
		public Keyword getNegaKeyword_4() { return cNegaKeyword_4; }
		
		//nega=Expressao
		public Assignment getNegaAssignment_5() { return cNegaAssignment_5; }
		
		//Expressao
		public RuleCall getNegaExpressaoParserRuleCall_5_0() { return cNegaExpressaoParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final ProgramaElements pPrograma;
	private final ComandoElements pComando;
	private final ExpressaoElements pExpressao;
	private final EStringElements pEString;
	private final BlocoElements pBloco;
	private final VariavelElements pVariavel;
	private final ProcedimentoElements pProcedimento;
	private final CallProcedimentoElements pCallProcedimento;
	private final AtribuicaoElements pAtribuicao;
	private final DesvioElements pDesvio;
	private final LoopElements pLoop;
	private final EBigDecimalElements pEBigDecimal;
	private final CallProcElements pCallProc;
	private final CallVariavelElements pCallVariavel;
	private final NumberElements pNumber;
	private final ExpBinLogicaElements pExpBinLogica;
	private final ExpBinElements pExpBin;
	private final OT_COMPARISONElements pOT_COMPARISON;
	private final OT_ARITHMETICElements pOT_ARITHMETIC;
	private final OT_ASSIGNMENTElements pOT_ASSIGNMENT;
	private final OT_NEGATEElements pOT_NEGATE;
	private final ExpNegElements pExpNeg;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PascalitoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPrograma = new ProgramaElements();
		this.pComando = new ComandoElements();
		this.pExpressao = new ExpressaoElements();
		this.pEString = new EStringElements();
		this.pBloco = new BlocoElements();
		this.pVariavel = new VariavelElements();
		this.pProcedimento = new ProcedimentoElements();
		this.pCallProcedimento = new CallProcedimentoElements();
		this.pAtribuicao = new AtribuicaoElements();
		this.pDesvio = new DesvioElements();
		this.pLoop = new LoopElements();
		this.pEBigDecimal = new EBigDecimalElements();
		this.pCallProc = new CallProcElements();
		this.pCallVariavel = new CallVariavelElements();
		this.pNumber = new NumberElements();
		this.pExpBinLogica = new ExpBinLogicaElements();
		this.pExpBin = new ExpBinElements();
		this.pOT_COMPARISON = new OT_COMPARISONElements();
		this.pOT_ARITHMETIC = new OT_ARITHMETICElements();
		this.pOT_ASSIGNMENT = new OT_ASSIGNMENTElements();
		this.pOT_NEGATE = new OT_NEGATEElements();
		this.pExpNeg = new ExpNegElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Pascalito".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programa:
	//	'programa' Ident=EString
	//	'{'
	//	bloco=Bloco
	//	'}';
	public ProgramaElements getProgramaAccess() {
		return pPrograma;
	}
	
	public ParserRule getProgramaRule() {
		return getProgramaAccess().getRule();
	}
	
	//Comando:
	//	CallProcedimento | Atribuicao | Desvio | Loop;
	public ComandoElements getComandoAccess() {
		return pComando;
	}
	
	public ParserRule getComandoRule() {
		return getComandoAccess().getRule();
	}
	
	//Expressao:
	//	CallVariavel | CallProc | Number | ExpBinLogica | ExpBin | ExpNeg;
	public ExpressaoElements getExpressaoAccess() {
		return pExpressao;
	}
	
	public ParserRule getExpressaoRule() {
		return getExpressaoAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Bloco:
	//	{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento'
	//	defprocedimento+=Procedimento)*
	//	'Inicio' executa+=Comando* 'Fim';
	public BlocoElements getBlocoAccess() {
		return pBloco;
	}
	
	public ParserRule getBlocoRule() {
		return getBlocoAccess().getRule();
	}
	
	//Variavel:
	//	{Variavel} name=ID
	//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
	//;
	public VariavelElements getVariavelAccess() {
		return pVariavel;
	}
	
	public ParserRule getVariavelRule() {
		return getVariavelAccess().getRule();
	}
	
	//Procedimento:
	//	(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
	//	"{"
	//	bloco=Bloco
	//	"}";
	public ProcedimentoElements getProcedimentoAccess() {
		return pProcedimento;
	}
	
	public ParserRule getProcedimentoRule() {
		return getProcedimentoAccess().getRule();
	}
	
	//CallProcedimento:
	//	definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
	//	';';
	public CallProcedimentoElements getCallProcedimentoAccess() {
		return pCallProcedimento;
	}
	
	public ParserRule getCallProcedimentoRule() {
		return getCallProcedimentoAccess().getRule();
	}
	
	//Atribuicao:
	//	atribui=[Variavel] OT_ASSIGNMENT atribuiResultado=Expressao ';';
	public AtribuicaoElements getAtribuicaoAccess() {
		return pAtribuicao;
	}
	
	public ParserRule getAtribuicaoRule() {
		return getAtribuicaoAccess().getRule();
	}
	
	//Desvio:
	//	'if' '(' se=Expressao ')'
	//	'{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?;
	public DesvioElements getDesvioAccess() {
		return pDesvio;
	}
	
	public ParserRule getDesvioRule() {
		return getDesvioAccess().getRule();
	}
	
	//Loop:
	//	'Loop' '(' se=Expressao ')'
	//	'{' faca+=Comando* '}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//EBigDecimal ecore::EBigDecimal:
	//	INT? '.' INT
	public EBigDecimalElements getEBigDecimalAccess() {
		return pEBigDecimal;
	}
	
	public ParserRule getEBigDecimalRule() {
		return getEBigDecimalAccess().getRule();
	}
	
	//CallProc:
	//	representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')');
	public CallProcElements getCallProcAccess() {
		return pCallProc;
	}
	
	public ParserRule getCallProcRule() {
		return getCallProcAccess().getRule();
	}
	
	//CallVariavel:
	//	representa=[Variavel];
	public CallVariavelElements getCallVariavelAccess() {
		return pCallVariavel;
	}
	
	public ParserRule getCallVariavelRule() {
		return getCallVariavelAccess().getRule();
	}
	
	//Number:
	//	{Number} Valor=EInt;
	public NumberElements getNumberAccess() {
		return pNumber;
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}
	
	//ExpBinLogica:
	//	Comutativa?='Comutativa'?
	//	'ExpBinLogica'
	//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
	//	'operandoEsq' operandoEsq=Expressao
	//	'operandoDir' operandoDir=Expressao
	//	'}';
	public ExpBinLogicaElements getExpBinLogicaAccess() {
		return pExpBinLogica;
	}
	
	public ParserRule getExpBinLogicaRule() {
		return getExpBinLogicaAccess().getRule();
	}
	
	//ExpBin:
	//	Comutativa?='Comutativa'?
	//	'ExpBin'
	//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
	//	'operandoDir' operandoDir=Expressao
	//	'operandoEsq' operandoEsq=Expressao
	//	'}';
	public ExpBinElements getExpBinAccess() {
		return pExpBin;
	}
	
	public ParserRule getExpBinRule() {
		return getExpBinAccess().getRule();
	}
	
	////terminal 
	//OT_COMPARISON:
	//	'<' | '>' | '=<' | '>=' | '==';
	public OT_COMPARISONElements getOT_COMPARISONAccess() {
		return pOT_COMPARISON;
	}
	
	public ParserRule getOT_COMPARISONRule() {
		return getOT_COMPARISONAccess().getRule();
	}
	
	////terminal 
	//OT_ARITHMETIC:
	//	'-' | '+' | '*' | '/';
	public OT_ARITHMETICElements getOT_ARITHMETICAccess() {
		return pOT_ARITHMETIC;
	}
	
	public ParserRule getOT_ARITHMETICRule() {
		return getOT_ARITHMETICAccess().getRule();
	}
	
	////terminal 
	//OT_ASSIGNMENT:
	//	'->';
	public OT_ASSIGNMENTElements getOT_ASSIGNMENTAccess() {
		return pOT_ASSIGNMENT;
	}
	
	public ParserRule getOT_ASSIGNMENTRule() {
		return getOT_ASSIGNMENTAccess().getRule();
	}
	
	////terminal 
	//OT_NEGATE:
	//	'-';
	public OT_NEGATEElements getOT_NEGATEAccess() {
		return pOT_NEGATE;
	}
	
	public ParserRule getOT_NEGATERule() {
		return getOT_NEGATEAccess().getRule();
	}
	
	//ExpNeg:
	//	'ExpNeg'
	//	'{' ('Prioridade' Prioridade=EBigDecimal)? ('Operador' Operador=EString)?
	//	'nega' nega=Expressao
	//	'}';
	public ExpNegElements getExpNegAccess() {
		return pExpNeg;
	}
	
	public ParserRule getExpNegRule() {
		return getExpNegAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
