/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PascalitoGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Programa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentEStringParserRuleCall_1_0 = (RuleCall)cIdentAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBlocoAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBlocoBlocoParserRuleCall_3_0 = (RuleCall)cBlocoAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Programa:
		//	'programa' Ident=EString
		//	'{'
		//	bloco=Bloco
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'programa' Ident=EString '{' bloco=Bloco '}'
		public Group getGroup() { return cGroup; }
		
		//'programa'
		public Keyword getProgramaKeyword_0() { return cProgramaKeyword_0; }
		
		//Ident=EString
		public Assignment getIdentAssignment_1() { return cIdentAssignment_1; }
		
		//EString
		public RuleCall getIdentEStringParserRuleCall_1_0() { return cIdentEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//bloco=Bloco
		public Assignment getBlocoAssignment_3() { return cBlocoAssignment_3; }
		
		//Bloco
		public RuleCall getBlocoBlocoParserRuleCall_3_0() { return cBlocoBlocoParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ComandoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Comando");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallProcedimentoParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAtribuicaoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDesvioParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLoopParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Comando:
		//	CallProcedimento | Atribuicao | Desvio | Loop;
		@Override public ParserRule getRule() { return rule; }
		
		//CallProcedimento | Atribuicao | Desvio | Loop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallProcedimento
		public RuleCall getCallProcedimentoParserRuleCall_0() { return cCallProcedimentoParserRuleCall_0; }
		
		//Atribuicao
		public RuleCall getAtribuicaoParserRuleCall_1() { return cAtribuicaoParserRuleCall_1; }
		
		//Desvio
		public RuleCall getDesvioParserRuleCall_2() { return cDesvioParserRuleCall_2; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_3() { return cLoopParserRuleCall_3; }
	}
	public class ExpressaoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Expressao");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExpNegParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComutativaParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Expressao:
		//	ExpNeg | Comutativa;
		@Override public ParserRule getRule() { return rule; }
		
		//ExpNeg | Comutativa
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExpNeg
		public RuleCall getExpNegParserRuleCall_0() { return cExpNegParserRuleCall_0; }
		
		//Comutativa
		public RuleCall getComutativaParserRuleCall_1() { return cComutativaParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BlocoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Bloco");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlocoAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVarKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDefvariavelAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDefvariavelVariavelParserRuleCall_1_1_0 = (RuleCall)cDefvariavelAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cDefvariavelAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cDefvariavelVariavelParserRuleCall_1_2_1_0 = (RuleCall)cDefvariavelAssignment_1_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cProcedimentoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDefprocedimentoAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDefprocedimentoProcedimentoParserRuleCall_2_1_0 = (RuleCall)cDefprocedimentoAssignment_2_1.eContents().get(0);
		private final Keyword cInicioKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExecutaAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExecutaComandoParserRuleCall_4_0 = (RuleCall)cExecutaAssignment_4.eContents().get(0);
		private final Keyword cFimKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Bloco:
		//	{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento'
		//	defprocedimento+=Procedimento)*
		//	'inicio' executa+=Comando* 'fim';
		@Override public ParserRule getRule() { return rule; }
		
		//{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento' defprocedimento+=Procedimento)*
		//'inicio' executa+=Comando* 'fim'
		public Group getGroup() { return cGroup; }
		
		//{Bloco}
		public Action getBlocoAction_0() { return cBlocoAction_0; }
		
		//('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")*
		public Group getGroup_1() { return cGroup_1; }
		
		//'var'
		public Keyword getVarKeyword_1_0() { return cVarKeyword_1_0; }
		
		//defvariavel+=Variavel
		public Assignment getDefvariavelAssignment_1_1() { return cDefvariavelAssignment_1_1; }
		
		//Variavel
		public RuleCall getDefvariavelVariavelParserRuleCall_1_1_0() { return cDefvariavelVariavelParserRuleCall_1_1_0; }
		
		//("," defvariavel+=Variavel)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//defvariavel+=Variavel
		public Assignment getDefvariavelAssignment_1_2_1() { return cDefvariavelAssignment_1_2_1; }
		
		//Variavel
		public RuleCall getDefvariavelVariavelParserRuleCall_1_2_1_0() { return cDefvariavelVariavelParserRuleCall_1_2_1_0; }
		
		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
		
		//('procedimento' defprocedimento+=Procedimento)*
		public Group getGroup_2() { return cGroup_2; }
		
		//'procedimento'
		public Keyword getProcedimentoKeyword_2_0() { return cProcedimentoKeyword_2_0; }
		
		//defprocedimento+=Procedimento
		public Assignment getDefprocedimentoAssignment_2_1() { return cDefprocedimentoAssignment_2_1; }
		
		//Procedimento
		public RuleCall getDefprocedimentoProcedimentoParserRuleCall_2_1_0() { return cDefprocedimentoProcedimentoParserRuleCall_2_1_0; }
		
		//'inicio'
		public Keyword getInicioKeyword_3() { return cInicioKeyword_3; }
		
		//executa+=Comando*
		public Assignment getExecutaAssignment_4() { return cExecutaAssignment_4; }
		
		//Comando
		public RuleCall getExecutaComandoParserRuleCall_4_0() { return cExecutaComandoParserRuleCall_4_0; }
		
		//'fim'
		public Keyword getFimKeyword_5() { return cFimKeyword_5; }
	}
	public class VariavelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Variavel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariavelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Variavel:
		//	{Variavel} name=ID
		//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variavel} name=ID
		public Group getGroup() { return cGroup; }
		
		//{Variavel}
		public Action getVariavelAction_0() { return cVariavelAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class ProcedimentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Procedimento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Assignment cParametroAssignment_0_2_0 = (Assignment)cGroup_0_2.eContents().get(0);
		private final RuleCall cParametroVariavelParserRuleCall_0_2_0_0 = (RuleCall)cParametroAssignment_0_2_0.eContents().get(0);
		private final Group cGroup_0_2_1 = (Group)cGroup_0_2.eContents().get(1);
		private final Keyword cCommaKeyword_0_2_1_0 = (Keyword)cGroup_0_2_1.eContents().get(0);
		private final Assignment cParametroAssignment_0_2_1_1 = (Assignment)cGroup_0_2_1.eContents().get(1);
		private final RuleCall cParametroVariavelParserRuleCall_0_2_1_1_0 = (RuleCall)cParametroAssignment_0_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBlocoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBlocoBlocoParserRuleCall_2_0 = (RuleCall)cBlocoAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Procedimento:
		//	(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
		//	"{"
		//	bloco=Bloco
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")") "{" bloco=Bloco "}"
		public Group getGroup() { return cGroup; }
		
		//(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
		public Group getGroup_0() { return cGroup_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0_0() { return cNameIDTerminalRuleCall_0_0_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//(parametro+=Variavel ("," parametro+=Variavel)*)?
		public Group getGroup_0_2() { return cGroup_0_2; }
		
		//parametro+=Variavel
		public Assignment getParametroAssignment_0_2_0() { return cParametroAssignment_0_2_0; }
		
		//Variavel
		public RuleCall getParametroVariavelParserRuleCall_0_2_0_0() { return cParametroVariavelParserRuleCall_0_2_0_0; }
		
		//("," parametro+=Variavel)*
		public Group getGroup_0_2_1() { return cGroup_0_2_1; }
		
		//","
		public Keyword getCommaKeyword_0_2_1_0() { return cCommaKeyword_0_2_1_0; }
		
		//parametro+=Variavel
		public Assignment getParametroAssignment_0_2_1_1() { return cParametroAssignment_0_2_1_1; }
		
		//Variavel
		public RuleCall getParametroVariavelParserRuleCall_0_2_1_1_0() { return cParametroVariavelParserRuleCall_0_2_1_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//bloco=Bloco
		public Assignment getBlocoAssignment_2() { return cBlocoAssignment_2; }
		
		//Bloco
		public RuleCall getBlocoBlocoParserRuleCall_2_0() { return cBlocoBlocoParserRuleCall_2_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class CallProcedimentoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProcedimento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDefinidoAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cDefinidoProcedimentoCrossReference_0_0 = (CrossReference)cDefinidoAssignment_0.eContents().get(0);
		private final RuleCall cDefinidoProcedimentoIDTerminalRuleCall_0_0_1 = (RuleCall)cDefinidoProcedimentoCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParametroAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_0_0 = (RuleCall)cParametroAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParametroAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_1_1_0 = (RuleCall)cParametroAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//CallProcedimento:
		//	definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')') ';'
		public Group getGroup() { return cGroup; }
		
		//definido=[Procedimento]
		public Assignment getDefinidoAssignment_0() { return cDefinidoAssignment_0; }
		
		//[Procedimento]
		public CrossReference getDefinidoProcedimentoCrossReference_0_0() { return cDefinidoProcedimentoCrossReference_0_0; }
		
		//ID
		public RuleCall getDefinidoProcedimentoIDTerminalRuleCall_0_0_1() { return cDefinidoProcedimentoIDTerminalRuleCall_0_0_1; }
		
		//('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parametro+=Expressao ("," parametro+=Expressao)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_0() { return cParametroAssignment_1_1_0; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_0_0() { return cParametroExpressaoParserRuleCall_1_1_0_0; }
		
		//("," parametro+=Expressao)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_1_1() { return cParametroAssignment_1_1_1_1; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_1_1_0() { return cParametroExpressaoParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class AtribuicaoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Atribuicao");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAtribuiAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cAtribuiVariavelCrossReference_0_0 = (CrossReference)cAtribuiAssignment_0.eContents().get(0);
		private final RuleCall cAtribuiVariavelIDTerminalRuleCall_0_0_1 = (RuleCall)cAtribuiVariavelCrossReference_0_0.eContents().get(1);
		private final RuleCall cOP_ASSIGNMENTParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cAtribuiResultadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAtribuiResultadoExpressaoParserRuleCall_2_0 = (RuleCall)cAtribuiResultadoAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Atribuicao:
		//	atribui=[Variavel] OP_ASSIGNMENT atribuiResultado=Expressao ';';
		@Override public ParserRule getRule() { return rule; }
		
		//atribui=[Variavel] OP_ASSIGNMENT atribuiResultado=Expressao ';'
		public Group getGroup() { return cGroup; }
		
		//atribui=[Variavel]
		public Assignment getAtribuiAssignment_0() { return cAtribuiAssignment_0; }
		
		//[Variavel]
		public CrossReference getAtribuiVariavelCrossReference_0_0() { return cAtribuiVariavelCrossReference_0_0; }
		
		//ID
		public RuleCall getAtribuiVariavelIDTerminalRuleCall_0_0_1() { return cAtribuiVariavelIDTerminalRuleCall_0_0_1; }
		
		//OP_ASSIGNMENT
		public RuleCall getOP_ASSIGNMENTParserRuleCall_1() { return cOP_ASSIGNMENTParserRuleCall_1; }
		
		//atribuiResultado=Expressao
		public Assignment getAtribuiResultadoAssignment_2() { return cAtribuiResultadoAssignment_2; }
		
		//Expressao
		public RuleCall getAtribuiResultadoExpressaoParserRuleCall_2_0() { return cAtribuiResultadoExpressaoParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class DesvioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Desvio");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSeExpressaoParserRuleCall_2_0 = (RuleCall)cSeAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFacaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFacaComandoParserRuleCall_5_0 = (RuleCall)cFacaAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cElseKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cSeNaoAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cSeNaoComandoParserRuleCall_7_2_0 = (RuleCall)cSeNaoAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//Desvio:
		//	'if' '(' se=Expressao ')'
		//	'{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'if' '(' se=Expressao ')' '{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?
		public Group getGroup() { return cGroup; }
		
		//'if'
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//se=Expressao
		public Assignment getSeAssignment_2() { return cSeAssignment_2; }
		
		//Expressao
		public RuleCall getSeExpressaoParserRuleCall_2_0() { return cSeExpressaoParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//faca+=Comando*
		public Assignment getFacaAssignment_5() { return cFacaAssignment_5; }
		
		//Comando
		public RuleCall getFacaComandoParserRuleCall_5_0() { return cFacaComandoParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//('else' '{' seNao+=Comando* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'else'
		public Keyword getElseKeyword_7_0() { return cElseKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//seNao+=Comando*
		public Assignment getSeNaoAssignment_7_2() { return cSeNaoAssignment_7_2; }
		
		//Comando
		public RuleCall getSeNaoComandoParserRuleCall_7_2_0() { return cSeNaoComandoParserRuleCall_7_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSeExpressaoParserRuleCall_2_0 = (RuleCall)cSeAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFacaAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFacaComandoParserRuleCall_5_0 = (RuleCall)cFacaAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loop:
		//	'Loop' '(' se=Expressao ')'
		//	'{' faca+=Comando* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loop' '(' se=Expressao ')' '{' faca+=Comando* '}'
		public Group getGroup() { return cGroup; }
		
		//'Loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//se=Expressao
		public Assignment getSeAssignment_2() { return cSeAssignment_2; }
		
		//Expressao
		public RuleCall getSeExpressaoParserRuleCall_2_0() { return cSeExpressaoParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//faca+=Comando*
		public Assignment getFacaAssignment_5() { return cFacaAssignment_5; }
		
		//Comando
		public RuleCall getFacaComandoParserRuleCall_5_0() { return cFacaComandoParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class CallProcElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRepresentaProcAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRepresentaProcProcedimentoCrossReference_0_0 = (CrossReference)cRepresentaProcAssignment_0.eContents().get(0);
		private final RuleCall cRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1 = (RuleCall)cRepresentaProcProcedimentoCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParametroAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_0_0 = (RuleCall)cParametroAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParametroAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParametroExpressaoParserRuleCall_1_1_1_1_0 = (RuleCall)cParametroAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//CallProc:
		//	representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')');
		@Override public ParserRule getRule() { return rule; }
		
		//representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup() { return cGroup; }
		
		//representaProc=[Procedimento]
		public Assignment getRepresentaProcAssignment_0() { return cRepresentaProcAssignment_0; }
		
		//[Procedimento]
		public CrossReference getRepresentaProcProcedimentoCrossReference_0_0() { return cRepresentaProcProcedimentoCrossReference_0_0; }
		
		//ID
		public RuleCall getRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1() { return cRepresentaProcProcedimentoIDTerminalRuleCall_0_0_1; }
		
		//('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parametro+=Expressao ("," parametro+=Expressao)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_0() { return cParametroAssignment_1_1_0; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_0_0() { return cParametroExpressaoParserRuleCall_1_1_0_0; }
		
		//("," parametro+=Expressao)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parametro+=Expressao
		public Assignment getParametroAssignment_1_1_1_1() { return cParametroAssignment_1_1_1_1; }
		
		//Expressao
		public RuleCall getParametroExpressaoParserRuleCall_1_1_1_1_0() { return cParametroExpressaoParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class CallVariavelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallVariavel");
		private final Assignment cRepresentaAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cRepresentaVariavelCrossReference_0 = (CrossReference)cRepresentaAssignment.eContents().get(0);
		private final RuleCall cRepresentaVariavelIDTerminalRuleCall_0_1 = (RuleCall)cRepresentaVariavelCrossReference_0.eContents().get(1);
		
		//CallVariavel:
		//	representa=[Variavel];
		@Override public ParserRule getRule() { return rule; }
		
		//representa=[Variavel]
		public Assignment getRepresentaAssignment() { return cRepresentaAssignment; }
		
		//[Variavel]
		public CrossReference getRepresentaVariavelCrossReference_0() { return cRepresentaVariavelCrossReference_0; }
		
		//ID
		public RuleCall getRepresentaVariavelIDTerminalRuleCall_0_1() { return cRepresentaVariavelIDTerminalRuleCall_0_1; }
	}
	public class ComutativaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Comutativa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cN_ComutativaParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cComutativaLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_ARIT_PRIO_0ParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightN_ComutativaParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Comutativa Expressao:
		//	N_Comutativa ({Comutativa.left=current} OP_ARIT_PRIO_0 right=N_Comutativa)*
		@Override public ParserRule getRule() { return rule; }
		
		//N_Comutativa ({Comutativa.left=current} OP_ARIT_PRIO_0 right=N_Comutativa)*
		public Group getGroup() { return cGroup; }
		
		//N_Comutativa
		public RuleCall getN_ComutativaParserRuleCall_0() { return cN_ComutativaParserRuleCall_0; }
		
		//({Comutativa.left=current} OP_ARIT_PRIO_0 right=N_Comutativa)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Comutativa.left=current}
		public Action getComutativaLeftAction_1_0() { return cComutativaLeftAction_1_0; }
		
		//OP_ARIT_PRIO_0
		public RuleCall getOP_ARIT_PRIO_0ParserRuleCall_1_1() { return cOP_ARIT_PRIO_0ParserRuleCall_1_1; }
		
		//right=N_Comutativa
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//N_Comutativa
		public RuleCall getRightN_ComutativaParserRuleCall_1_2_0() { return cRightN_ComutativaParserRuleCall_1_2_0; }
	}
	public class N_ComutativaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.N_Comutativa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExpBinLogicaParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cN_ComutativaLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_ARIT_PRIO_1ParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpBinLogicaParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//N_Comutativa Expressao:
		//	ExpBinLogica ({N_Comutativa.left=current} OP_ARIT_PRIO_1 right=ExpBinLogica)*
		@Override public ParserRule getRule() { return rule; }
		
		//ExpBinLogica ({N_Comutativa.left=current} OP_ARIT_PRIO_1 right=ExpBinLogica)*
		public Group getGroup() { return cGroup; }
		
		//ExpBinLogica
		public RuleCall getExpBinLogicaParserRuleCall_0() { return cExpBinLogicaParserRuleCall_0; }
		
		//({N_Comutativa.left=current} OP_ARIT_PRIO_1 right=ExpBinLogica)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{N_Comutativa.left=current}
		public Action getN_ComutativaLeftAction_1_0() { return cN_ComutativaLeftAction_1_0; }
		
		//OP_ARIT_PRIO_1
		public RuleCall getOP_ARIT_PRIO_1ParserRuleCall_1_1() { return cOP_ARIT_PRIO_1ParserRuleCall_1_1; }
		
		//right=ExpBinLogica
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//ExpBinLogica
		public RuleCall getRightExpBinLogicaParserRuleCall_1_2_0() { return cRightExpBinLogicaParserRuleCall_1_2_0; }
	}
	public class ExpBinLogicaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBinLogica");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpBinLogicaLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_COMPARISONParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ExpBinLogica Expressao:
		//	Primary ({ExpBinLogica.left=current} OP_COMPARISON right=Primary)*
		@Override public ParserRule getRule() { return rule; }
		
		//Primary ({ExpBinLogica.left=current} OP_COMPARISON right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({ExpBinLogica.left=current} OP_COMPARISON right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{ExpBinLogica.left=current}
		public Action getExpBinLogicaLeftAction_1_0() { return cExpBinLogicaLeftAction_1_0; }
		
		//OP_COMPARISON
		public RuleCall getOP_COMPARISONParserRuleCall_1_1() { return cOP_COMPARISONParserRuleCall_1_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumberLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCallProcParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCallVariavelParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cComutativaParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Primary Expressao:
		//	NumberLiteral | CallProc | CallVariavel |
		//	'(' Comutativa ')'
		@Override public ParserRule getRule() { return rule; }
		
		//NumberLiteral | CallProc | CallVariavel | '(' Comutativa ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NumberLiteral
		public RuleCall getNumberLiteralParserRuleCall_0() { return cNumberLiteralParserRuleCall_0; }
		
		//CallProc
		public RuleCall getCallProcParserRuleCall_1() { return cCallProcParserRuleCall_1; }
		
		//CallVariavel
		public RuleCall getCallVariavelParserRuleCall_2() { return cCallVariavelParserRuleCall_2; }
		
		//'(' Comutativa ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//Comutativa
		public RuleCall getComutativaParserRuleCall_3_1() { return cComutativaParserRuleCall_3_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
	}
	public class NumberLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.NumberLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cEBigDecimalParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//NumberLiteral:
		//	{NumberLiteral} EBigDecimal;
		@Override public ParserRule getRule() { return rule; }
		
		//{NumberLiteral} EBigDecimal
		public Group getGroup() { return cGroup; }
		
		//{NumberLiteral}
		public Action getNumberLiteralAction_0() { return cNumberLiteralAction_0; }
		
		//EBigDecimal
		public RuleCall getEBigDecimalParserRuleCall_1() { return cEBigDecimalParserRuleCall_1; }
	}
	public class EBigDecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBigDecimal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		
		//EBigDecimal ecore::EBigDecimal:
		//	INT | INT '.' INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT | INT '.' INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//INT '.' INT
		public Group getGroup_1() { return cGroup_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_0() { return cINTTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1() { return cFullStopKeyword_1_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_2() { return cINTTerminalRuleCall_1_2; }
	}
	public class ExpNegElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpNeg");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOP_NEGATEParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cNegaAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNegaExpressaoParserRuleCall_1_0 = (RuleCall)cNegaAssignment_1.eContents().get(0);
		
		//ExpNeg:
		//	OP_NEGATE nega=Expressao;
		@Override public ParserRule getRule() { return rule; }
		
		//OP_NEGATE nega=Expressao
		public Group getGroup() { return cGroup; }
		
		//OP_NEGATE
		public RuleCall getOP_NEGATEParserRuleCall_0() { return cOP_NEGATEParserRuleCall_0; }
		
		//nega=Expressao
		public Assignment getNegaAssignment_1() { return cNegaAssignment_1; }
		
		//Expressao
		public RuleCall getNegaExpressaoParserRuleCall_1_0() { return cNegaExpressaoParserRuleCall_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class OP_COMPARISONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_COMPARISON");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEqualsSignLessThanSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cEqualsSignEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cANDKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cORKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final Keyword cXORKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		
		////terminal 
		//OP_COMPARISON:
		//	'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR';
		@Override public ParserRule getRule() { return rule; }
		
		//'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'<'
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1() { return cGreaterThanSignKeyword_1; }
		
		//'=<'
		public Keyword getEqualsSignLessThanSignKeyword_2() { return cEqualsSignLessThanSignKeyword_2; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_3() { return cGreaterThanSignEqualsSignKeyword_3; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_4() { return cEqualsSignEqualsSignKeyword_4; }
		
		//'AND'
		public Keyword getANDKeyword_5() { return cANDKeyword_5; }
		
		//'OR'
		public Keyword getORKeyword_6() { return cORKeyword_6; }
		
		//'XOR'
		public Keyword getXORKeyword_7() { return cXORKeyword_7; }
	}
	public class OP_ARIT_PRIO_0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ARIT_PRIO_0");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cPlusSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		////terminal 
		//OP_ARIT_PRIO_0:
		//	'-' | '+';
		@Override public ParserRule getRule() { return rule; }
		
		//'-' | '+'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1() { return cPlusSignKeyword_1; }
	}
	public class OP_ARIT_PRIO_1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ARIT_PRIO_1");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSolidusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//OP_ARIT_PRIO_1:
		//	'*' | '/';
		@Override public ParserRule getRule() { return rule; }
		
		//'*' | '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1() { return cSolidusKeyword_1; }
	}
	public class OP_ASSIGNMENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ASSIGNMENT");
		private final Keyword cHyphenMinusGreaterThanSignKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OP_ASSIGNMENT:
		//	'->';
		@Override public ParserRule getRule() { return rule; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword() { return cHyphenMinusGreaterThanSignKeyword; }
	}
	public class OP_NEGATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_NEGATE");
		private final Keyword cHyphenMinusKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OP_NEGATE:
		//	'-';
		@Override public ParserRule getRule() { return rule; }
		
		//'-'
		public Keyword getHyphenMinusKeyword() { return cHyphenMinusKeyword; }
	}
	
	
	private final ProgramaElements pPrograma;
	private final ComandoElements pComando;
	private final ExpressaoElements pExpressao;
	private final EStringElements pEString;
	private final BlocoElements pBloco;
	private final VariavelElements pVariavel;
	private final ProcedimentoElements pProcedimento;
	private final CallProcedimentoElements pCallProcedimento;
	private final AtribuicaoElements pAtribuicao;
	private final DesvioElements pDesvio;
	private final LoopElements pLoop;
	private final CallProcElements pCallProc;
	private final CallVariavelElements pCallVariavel;
	private final ComutativaElements pComutativa;
	private final N_ComutativaElements pN_Comutativa;
	private final ExpBinLogicaElements pExpBinLogica;
	private final PrimaryElements pPrimary;
	private final NumberLiteralElements pNumberLiteral;
	private final EBigDecimalElements pEBigDecimal;
	private final ExpNegElements pExpNeg;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final OP_COMPARISONElements pOP_COMPARISON;
	private final OP_ARIT_PRIO_0Elements pOP_ARIT_PRIO_0;
	private final OP_ARIT_PRIO_1Elements pOP_ARIT_PRIO_1;
	private final OP_ASSIGNMENTElements pOP_ASSIGNMENT;
	private final OP_NEGATEElements pOP_NEGATE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PascalitoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPrograma = new ProgramaElements();
		this.pComando = new ComandoElements();
		this.pExpressao = new ExpressaoElements();
		this.pEString = new EStringElements();
		this.pBloco = new BlocoElements();
		this.pVariavel = new VariavelElements();
		this.pProcedimento = new ProcedimentoElements();
		this.pCallProcedimento = new CallProcedimentoElements();
		this.pAtribuicao = new AtribuicaoElements();
		this.pDesvio = new DesvioElements();
		this.pLoop = new LoopElements();
		this.pCallProc = new CallProcElements();
		this.pCallVariavel = new CallVariavelElements();
		this.pComutativa = new ComutativaElements();
		this.pN_Comutativa = new N_ComutativaElements();
		this.pExpBinLogica = new ExpBinLogicaElements();
		this.pPrimary = new PrimaryElements();
		this.pNumberLiteral = new NumberLiteralElements();
		this.pEBigDecimal = new EBigDecimalElements();
		this.pExpNeg = new ExpNegElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.pOP_COMPARISON = new OP_COMPARISONElements();
		this.pOP_ARIT_PRIO_0 = new OP_ARIT_PRIO_0Elements();
		this.pOP_ARIT_PRIO_1 = new OP_ARIT_PRIO_1Elements();
		this.pOP_ASSIGNMENT = new OP_ASSIGNMENTElements();
		this.pOP_NEGATE = new OP_NEGATEElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Pascalito".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Programa:
	//	'programa' Ident=EString
	//	'{'
	//	bloco=Bloco
	//	'}';
	public ProgramaElements getProgramaAccess() {
		return pPrograma;
	}
	
	public ParserRule getProgramaRule() {
		return getProgramaAccess().getRule();
	}
	
	//Comando:
	//	CallProcedimento | Atribuicao | Desvio | Loop;
	public ComandoElements getComandoAccess() {
		return pComando;
	}
	
	public ParserRule getComandoRule() {
		return getComandoAccess().getRule();
	}
	
	//Expressao:
	//	ExpNeg | Comutativa;
	public ExpressaoElements getExpressaoAccess() {
		return pExpressao;
	}
	
	public ParserRule getExpressaoRule() {
		return getExpressaoAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Bloco:
	//	{Bloco} ('var' defvariavel+=Variavel ("," defvariavel+=Variavel)* ";")* ('procedimento'
	//	defprocedimento+=Procedimento)*
	//	'inicio' executa+=Comando* 'fim';
	public BlocoElements getBlocoAccess() {
		return pBloco;
	}
	
	public ParserRule getBlocoRule() {
		return getBlocoAccess().getRule();
	}
	
	//Variavel:
	//	{Variavel} name=ID
	//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
	//;
	public VariavelElements getVariavelAccess() {
		return pVariavel;
	}
	
	public ParserRule getVariavelRule() {
		return getVariavelAccess().getRule();
	}
	
	//Procedimento:
	//	(name=ID "(" (parametro+=Variavel ("," parametro+=Variavel)*)? ")")
	//	"{"
	//	bloco=Bloco
	//	"}";
	public ProcedimentoElements getProcedimentoAccess() {
		return pProcedimento;
	}
	
	public ParserRule getProcedimentoRule() {
		return getProcedimentoAccess().getRule();
	}
	
	//CallProcedimento:
	//	definido=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')')
	//	';';
	public CallProcedimentoElements getCallProcedimentoAccess() {
		return pCallProcedimento;
	}
	
	public ParserRule getCallProcedimentoRule() {
		return getCallProcedimentoAccess().getRule();
	}
	
	//Atribuicao:
	//	atribui=[Variavel] OP_ASSIGNMENT atribuiResultado=Expressao ';';
	public AtribuicaoElements getAtribuicaoAccess() {
		return pAtribuicao;
	}
	
	public ParserRule getAtribuicaoRule() {
		return getAtribuicaoAccess().getRule();
	}
	
	//Desvio:
	//	'if' '(' se=Expressao ')'
	//	'{' faca+=Comando* '}' ('else' '{' seNao+=Comando* '}')?;
	public DesvioElements getDesvioAccess() {
		return pDesvio;
	}
	
	public ParserRule getDesvioRule() {
		return getDesvioAccess().getRule();
	}
	
	//Loop:
	//	'Loop' '(' se=Expressao ')'
	//	'{' faca+=Comando* '}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//CallProc:
	//	representaProc=[Procedimento] ('(' (parametro+=Expressao ("," parametro+=Expressao)*)? ')');
	public CallProcElements getCallProcAccess() {
		return pCallProc;
	}
	
	public ParserRule getCallProcRule() {
		return getCallProcAccess().getRule();
	}
	
	//CallVariavel:
	//	representa=[Variavel];
	public CallVariavelElements getCallVariavelAccess() {
		return pCallVariavel;
	}
	
	public ParserRule getCallVariavelRule() {
		return getCallVariavelAccess().getRule();
	}
	
	//Comutativa Expressao:
	//	N_Comutativa ({Comutativa.left=current} OP_ARIT_PRIO_0 right=N_Comutativa)*
	public ComutativaElements getComutativaAccess() {
		return pComutativa;
	}
	
	public ParserRule getComutativaRule() {
		return getComutativaAccess().getRule();
	}
	
	//N_Comutativa Expressao:
	//	ExpBinLogica ({N_Comutativa.left=current} OP_ARIT_PRIO_1 right=ExpBinLogica)*
	public N_ComutativaElements getN_ComutativaAccess() {
		return pN_Comutativa;
	}
	
	public ParserRule getN_ComutativaRule() {
		return getN_ComutativaAccess().getRule();
	}
	
	//ExpBinLogica Expressao:
	//	Primary ({ExpBinLogica.left=current} OP_COMPARISON right=Primary)*
	public ExpBinLogicaElements getExpBinLogicaAccess() {
		return pExpBinLogica;
	}
	
	public ParserRule getExpBinLogicaRule() {
		return getExpBinLogicaAccess().getRule();
	}
	
	//Primary Expressao:
	//	NumberLiteral | CallProc | CallVariavel |
	//	'(' Comutativa ')'
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//NumberLiteral:
	//	{NumberLiteral} EBigDecimal;
	public NumberLiteralElements getNumberLiteralAccess() {
		return pNumberLiteral;
	}
	
	public ParserRule getNumberLiteralRule() {
		return getNumberLiteralAccess().getRule();
	}
	
	//EBigDecimal ecore::EBigDecimal:
	//	INT | INT '.' INT
	public EBigDecimalElements getEBigDecimalAccess() {
		return pEBigDecimal;
	}
	
	public ParserRule getEBigDecimalRule() {
		return getEBigDecimalAccess().getRule();
	}
	
	//ExpNeg:
	//	OP_NEGATE nega=Expressao;
	public ExpNegElements getExpNegAccess() {
		return pExpNeg;
	}
	
	public ParserRule getExpNegRule() {
		return getExpNegAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	////terminal 
	//OP_COMPARISON:
	//	'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR';
	public OP_COMPARISONElements getOP_COMPARISONAccess() {
		return pOP_COMPARISON;
	}
	
	public ParserRule getOP_COMPARISONRule() {
		return getOP_COMPARISONAccess().getRule();
	}
	
	////terminal 
	//OP_ARIT_PRIO_0:
	//	'-' | '+';
	public OP_ARIT_PRIO_0Elements getOP_ARIT_PRIO_0Access() {
		return pOP_ARIT_PRIO_0;
	}
	
	public ParserRule getOP_ARIT_PRIO_0Rule() {
		return getOP_ARIT_PRIO_0Access().getRule();
	}
	
	//OP_ARIT_PRIO_1:
	//	'*' | '/';
	public OP_ARIT_PRIO_1Elements getOP_ARIT_PRIO_1Access() {
		return pOP_ARIT_PRIO_1;
	}
	
	public ParserRule getOP_ARIT_PRIO_1Rule() {
		return getOP_ARIT_PRIO_1Access().getRule();
	}
	
	////terminal 
	//OP_ASSIGNMENT:
	//	'->';
	public OP_ASSIGNMENTElements getOP_ASSIGNMENTAccess() {
		return pOP_ASSIGNMENT;
	}
	
	public ParserRule getOP_ASSIGNMENTRule() {
		return getOP_ASSIGNMENTAccess().getRule();
	}
	
	////terminal 
	//OP_NEGATE:
	//	'-';
	public OP_NEGATEElements getOP_NEGATEAccess() {
		return pOP_NEGATE;
	}
	
	public ParserRule getOP_NEGATERule() {
		return getOP_NEGATEAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
