/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PascalitoGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdentAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdentEStringParserRuleCall_1_0 = (RuleCall)cIdentAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBlockAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBlockBlockParserRuleCall_3_0 = (RuleCall)cBlockAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Program:
		//	'program' Ident=EString
		//	'{'
		//	block=Block
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'program' Ident=EString '{' block=Block '}'
		public Group getGroup() { return cGroup; }
		
		//'program'
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }
		
		//Ident=EString
		public Assignment getIdentAssignment_1() { return cIdentAssignment_1; }
		
		//EString
		public RuleCall getIdentEStringParserRuleCall_1_0() { return cIdentEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//block=Block
		public Assignment getBlockAssignment_3() { return cBlockAssignment_3; }
		
		//Block
		public RuleCall getBlockBlockParserRuleCall_3_0() { return cBlockBlockParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class CommandElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Command");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCallProcParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAtribuitionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIfParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cLoopParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Command:
		//	CallProc | Atribuition | If | Loop;
		@Override public ParserRule getRule() { return rule; }
		
		//CallProc | Atribuition | If | Loop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CallProc
		public RuleCall getCallProcParserRuleCall_0() { return cCallProcParserRuleCall_0; }
		
		//Atribuition
		public RuleCall getAtribuitionParserRuleCall_1() { return cAtribuitionParserRuleCall_1; }
		
		//If
		public RuleCall getIfParserRuleCall_2() { return cIfParserRuleCall_2; }
		
		//Loop
		public RuleCall getLoopParserRuleCall_3() { return cLoopParserRuleCall_3; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExpNegParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cExpBinNv0ParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Expression:
		//	ExpNeg | ExpBinNv0;
		@Override public ParserRule getRule() { return rule; }
		
		//ExpNeg | ExpBinNv0
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExpNeg
		public RuleCall getExpNegParserRuleCall_0() { return cExpNegParserRuleCall_0; }
		
		//ExpBinNv0
		public RuleCall getExpBinNv0ParserRuleCall_1() { return cExpBinNv0ParserRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class BlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Block");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlockAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cVarKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cDefVariableAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cDefVariableVariableParserRuleCall_1_1_0 = (RuleCall)cDefVariableAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cDefVariableAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cDefVariableVariableParserRuleCall_1_2_1_0 = (RuleCall)cDefVariableAssignment_1_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cProcedureKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDefprocedureAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDefprocedureProcedureParserRuleCall_2_1_0 = (RuleCall)cDefprocedureAssignment_2_1.eContents().get(0);
		private final Keyword cStartKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExecuteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExecuteCommandParserRuleCall_4_0 = (RuleCall)cExecuteAssignment_4.eContents().get(0);
		private final Keyword cEndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Block:
		//	{Block} ('var' defVariable+=Variable ("," defVariable+=Variable)* ";")* ('procedure' defprocedure+=Procedure)*
		//	'start' execute+=Command* 'end';
		@Override public ParserRule getRule() { return rule; }
		
		//{Block} ('var' defVariable+=Variable ("," defVariable+=Variable)* ";")* ('procedure' defprocedure+=Procedure)* 'start'
		//execute+=Command* 'end'
		public Group getGroup() { return cGroup; }
		
		//{Block}
		public Action getBlockAction_0() { return cBlockAction_0; }
		
		//('var' defVariable+=Variable ("," defVariable+=Variable)* ";")*
		public Group getGroup_1() { return cGroup_1; }
		
		//'var'
		public Keyword getVarKeyword_1_0() { return cVarKeyword_1_0; }
		
		//defVariable+=Variable
		public Assignment getDefVariableAssignment_1_1() { return cDefVariableAssignment_1_1; }
		
		//Variable
		public RuleCall getDefVariableVariableParserRuleCall_1_1_0() { return cDefVariableVariableParserRuleCall_1_1_0; }
		
		//("," defVariable+=Variable)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//defVariable+=Variable
		public Assignment getDefVariableAssignment_1_2_1() { return cDefVariableAssignment_1_2_1; }
		
		//Variable
		public RuleCall getDefVariableVariableParserRuleCall_1_2_1_0() { return cDefVariableVariableParserRuleCall_1_2_1_0; }
		
		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }
		
		//('procedure' defprocedure+=Procedure)*
		public Group getGroup_2() { return cGroup_2; }
		
		//'procedure'
		public Keyword getProcedureKeyword_2_0() { return cProcedureKeyword_2_0; }
		
		//defprocedure+=Procedure
		public Assignment getDefprocedureAssignment_2_1() { return cDefprocedureAssignment_2_1; }
		
		//Procedure
		public RuleCall getDefprocedureProcedureParserRuleCall_2_1_0() { return cDefprocedureProcedureParserRuleCall_2_1_0; }
		
		//'start'
		public Keyword getStartKeyword_3() { return cStartKeyword_3; }
		
		//execute+=Command*
		public Assignment getExecuteAssignment_4() { return cExecuteAssignment_4; }
		
		//Command
		public RuleCall getExecuteCommandParserRuleCall_4_0() { return cExecuteCommandParserRuleCall_4_0; }
		
		//'end'
		public Keyword getEndKeyword_5() { return cEndKeyword_5; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Variable:
		//	{Variable} name=ID
		//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable} name=ID
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class ProcedureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Procedure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0_0 = (RuleCall)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_0_2 = (Group)cGroup_0.eContents().get(2);
		private final Assignment cParameterAssignment_0_2_0 = (Assignment)cGroup_0_2.eContents().get(0);
		private final RuleCall cParameterVariableParserRuleCall_0_2_0_0 = (RuleCall)cParameterAssignment_0_2_0.eContents().get(0);
		private final Group cGroup_0_2_1 = (Group)cGroup_0_2.eContents().get(1);
		private final Keyword cCommaKeyword_0_2_1_0 = (Keyword)cGroup_0_2_1.eContents().get(0);
		private final Assignment cParameterAssignment_0_2_1_1 = (Assignment)cGroup_0_2_1.eContents().get(1);
		private final RuleCall cParameterVariableParserRuleCall_0_2_1_1_0 = (RuleCall)cParameterAssignment_0_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBlockAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBlockBlockParserRuleCall_2_0 = (RuleCall)cBlockAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Procedure:
		//	(name=ID "(" (parameter+=Variable ("," parameter+=Variable)*)? ")")
		//	"{"
		//	block=Block
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//(name=ID "(" (parameter+=Variable ("," parameter+=Variable)*)? ")") "{" block=Block "}"
		public Group getGroup() { return cGroup; }
		
		//(name=ID "(" (parameter+=Variable ("," parameter+=Variable)*)? ")")
		public Group getGroup_0() { return cGroup_0; }
		
		//name=ID
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0_0() { return cNameIDTerminalRuleCall_0_0_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//(parameter+=Variable ("," parameter+=Variable)*)?
		public Group getGroup_0_2() { return cGroup_0_2; }
		
		//parameter+=Variable
		public Assignment getParameterAssignment_0_2_0() { return cParameterAssignment_0_2_0; }
		
		//Variable
		public RuleCall getParameterVariableParserRuleCall_0_2_0_0() { return cParameterVariableParserRuleCall_0_2_0_0; }
		
		//("," parameter+=Variable)*
		public Group getGroup_0_2_1() { return cGroup_0_2_1; }
		
		//","
		public Keyword getCommaKeyword_0_2_1_0() { return cCommaKeyword_0_2_1_0; }
		
		//parameter+=Variable
		public Assignment getParameterAssignment_0_2_1_1() { return cParameterAssignment_0_2_1_1; }
		
		//Variable
		public RuleCall getParameterVariableParserRuleCall_0_2_1_1_0() { return cParameterVariableParserRuleCall_0_2_1_1_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//block=Block
		public Assignment getBlockAssignment_2() { return cBlockAssignment_2; }
		
		//Block
		public RuleCall getBlockBlockParserRuleCall_2_0() { return cBlockBlockParserRuleCall_2_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class CallProcElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProc");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDefinedAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cDefinedProcedureCrossReference_0_0 = (CrossReference)cDefinedAssignment_0.eContents().get(0);
		private final RuleCall cDefinedProcedureIDTerminalRuleCall_0_0_1 = (RuleCall)cDefinedProcedureCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParameterAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParameterExpressionParserRuleCall_1_1_0_0 = (RuleCall)cParameterAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParameterAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParameterExpressionParserRuleCall_1_1_1_1_0 = (RuleCall)cParameterAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//CallProc:
		//	defined=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')')
		//	';';
		@Override public ParserRule getRule() { return rule; }
		
		//defined=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')') ';'
		public Group getGroup() { return cGroup; }
		
		//defined=[Procedure]
		public Assignment getDefinedAssignment_0() { return cDefinedAssignment_0; }
		
		//[Procedure]
		public CrossReference getDefinedProcedureCrossReference_0_0() { return cDefinedProcedureCrossReference_0_0; }
		
		//ID
		public RuleCall getDefinedProcedureIDTerminalRuleCall_0_0_1() { return cDefinedProcedureIDTerminalRuleCall_0_0_1; }
		
		//('(' (parameter+=Expression ("," parameter+=Expression)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parameter+=Expression ("," parameter+=Expression)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parameter+=Expression
		public Assignment getParameterAssignment_1_1_0() { return cParameterAssignment_1_1_0; }
		
		//Expression
		public RuleCall getParameterExpressionParserRuleCall_1_1_0_0() { return cParameterExpressionParserRuleCall_1_1_0_0; }
		
		//("," parameter+=Expression)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parameter+=Expression
		public Assignment getParameterAssignment_1_1_1_1() { return cParameterAssignment_1_1_1_1; }
		
		//Expression
		public RuleCall getParameterExpressionParserRuleCall_1_1_1_1_0() { return cParameterExpressionParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class AtribuitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Atribuition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSetsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cSetsVariableCrossReference_0_0 = (CrossReference)cSetsAssignment_0.eContents().get(0);
		private final RuleCall cSetsVariableIDTerminalRuleCall_0_0_1 = (RuleCall)cSetsVariableCrossReference_0_0.eContents().get(1);
		private final RuleCall cOP_ASSIGNMENTParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cAtribuiResultadoAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAtribuiResultadoExpressionParserRuleCall_2_0 = (RuleCall)cAtribuiResultadoAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Atribuition:
		//	sets=[Variable] OP_ASSIGNMENT atribuiResultado=Expression ';';
		@Override public ParserRule getRule() { return rule; }
		
		//sets=[Variable] OP_ASSIGNMENT atribuiResultado=Expression ';'
		public Group getGroup() { return cGroup; }
		
		//sets=[Variable]
		public Assignment getSetsAssignment_0() { return cSetsAssignment_0; }
		
		//[Variable]
		public CrossReference getSetsVariableCrossReference_0_0() { return cSetsVariableCrossReference_0_0; }
		
		//ID
		public RuleCall getSetsVariableIDTerminalRuleCall_0_0_1() { return cSetsVariableIDTerminalRuleCall_0_0_1; }
		
		//OP_ASSIGNMENT
		public RuleCall getOP_ASSIGNMENTParserRuleCall_1() { return cOP_ASSIGNMENTParserRuleCall_1; }
		
		//atribuiResultado=Expression
		public Assignment getAtribuiResultadoAssignment_2() { return cAtribuiResultadoAssignment_2; }
		
		//Expression
		public RuleCall getAtribuiResultadoExpressionParserRuleCall_2_0() { return cAtribuiResultadoExpressionParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class IfElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.If");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cIfExpAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cIfExpExpressionParserRuleCall_2_0 = (RuleCall)cIfExpAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDoCommandParserRuleCall_5_0 = (RuleCall)cDoAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cElseKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cElseCmdAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cElseCmdCommandParserRuleCall_7_2_0 = (RuleCall)cElseCmdAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//If:
		//	'if' '(' ifExp=Expression ')'
		//	'{' do+=Command* '}' ('else' '{' elseCmd+=Command* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'if' '(' ifExp=Expression ')' '{' do+=Command* '}' ('else' '{' elseCmd+=Command* '}')?
		public Group getGroup() { return cGroup; }
		
		//'if'
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//ifExp=Expression
		public Assignment getIfExpAssignment_2() { return cIfExpAssignment_2; }
		
		//Expression
		public RuleCall getIfExpExpressionParserRuleCall_2_0() { return cIfExpExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//do+=Command*
		public Assignment getDoAssignment_5() { return cDoAssignment_5; }
		
		//Command
		public RuleCall getDoCommandParserRuleCall_5_0() { return cDoCommandParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//('else' '{' elseCmd+=Command* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'else'
		public Keyword getElseKeyword_7_0() { return cElseKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//elseCmd+=Command*
		public Assignment getElseCmdAssignment_7_2() { return cElseCmdAssignment_7_2; }
		
		//Command
		public RuleCall getElseCmdCommandParserRuleCall_7_2_0() { return cElseCmdCommandParserRuleCall_7_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWhileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWhileExpressionParserRuleCall_2_0 = (RuleCall)cWhileAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDoCommandParserRuleCall_5_0 = (RuleCall)cDoAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Loop:
		//	'Loop' '(' while=Expression ')'
		//	'{' do+=Command* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Loop' '(' while=Expression ')' '{' do+=Command* '}'
		public Group getGroup() { return cGroup; }
		
		//'Loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//while=Expression
		public Assignment getWhileAssignment_2() { return cWhileAssignment_2; }
		
		//Expression
		public RuleCall getWhileExpressionParserRuleCall_2_0() { return cWhileExpressionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//do+=Command*
		public Assignment getDoAssignment_5() { return cDoAssignment_5; }
		
		//Command
		public RuleCall getDoCommandParserRuleCall_5_0() { return cDoCommandParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class CallProcExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallProcExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRepresentAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRepresentProcedureCrossReference_0_0 = (CrossReference)cRepresentAssignment_0.eContents().get(0);
		private final RuleCall cRepresentProcedureIDTerminalRuleCall_0_0_1 = (RuleCall)cRepresentProcedureCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Assignment cParameterAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cParameterExpressionParserRuleCall_1_1_0_0 = (RuleCall)cParameterAssignment_1_1_0.eContents().get(0);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cParameterAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final RuleCall cParameterExpressionParserRuleCall_1_1_1_1_0 = (RuleCall)cParameterAssignment_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		
		//CallProcExp:
		//	represent=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')');
		@Override public ParserRule getRule() { return rule; }
		
		//represent=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')')
		public Group getGroup() { return cGroup; }
		
		//represent=[Procedure]
		public Assignment getRepresentAssignment_0() { return cRepresentAssignment_0; }
		
		//[Procedure]
		public CrossReference getRepresentProcedureCrossReference_0_0() { return cRepresentProcedureCrossReference_0_0; }
		
		//ID
		public RuleCall getRepresentProcedureIDTerminalRuleCall_0_0_1() { return cRepresentProcedureIDTerminalRuleCall_0_0_1; }
		
		//('(' (parameter+=Expression ("," parameter+=Expression)*)? ')')
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(parameter+=Expression ("," parameter+=Expression)*)?
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//parameter+=Expression
		public Assignment getParameterAssignment_1_1_0() { return cParameterAssignment_1_1_0; }
		
		//Expression
		public RuleCall getParameterExpressionParserRuleCall_1_1_0_0() { return cParameterExpressionParserRuleCall_1_1_0_0; }
		
		//("," parameter+=Expression)*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//parameter+=Expression
		public Assignment getParameterAssignment_1_1_1_1() { return cParameterAssignment_1_1_1_1; }
		
		//Expression
		public RuleCall getParameterExpressionParserRuleCall_1_1_1_1_0() { return cParameterExpressionParserRuleCall_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class CallVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.CallVariable");
		private final Assignment cRepresentAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cRepresentVariableCrossReference_0 = (CrossReference)cRepresentAssignment.eContents().get(0);
		private final RuleCall cRepresentVariableIDTerminalRuleCall_0_1 = (RuleCall)cRepresentVariableCrossReference_0.eContents().get(1);
		
		//CallVariable:
		//	represent=[Variable];
		@Override public ParserRule getRule() { return rule; }
		
		//represent=[Variable]
		public Assignment getRepresentAssignment() { return cRepresentAssignment; }
		
		//[Variable]
		public CrossReference getRepresentVariableCrossReference_0() { return cRepresentVariableCrossReference_0; }
		
		//ID
		public RuleCall getRepresentVariableIDTerminalRuleCall_0_1() { return cRepresentVariableIDTerminalRuleCall_0_1; }
	}
	public class ExpBinNv0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBinNv0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExpBinNv1ParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpBinNv0LeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_ARIT_PRIO_0ParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpBinNv1ParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ExpBinNv0 Expression:
		//	ExpBinNv1 ({ExpBinNv0.left=current} OP_ARIT_PRIO_0 right=ExpBinNv1)*
		@Override public ParserRule getRule() { return rule; }
		
		//ExpBinNv1 ({ExpBinNv0.left=current} OP_ARIT_PRIO_0 right=ExpBinNv1)*
		public Group getGroup() { return cGroup; }
		
		//ExpBinNv1
		public RuleCall getExpBinNv1ParserRuleCall_0() { return cExpBinNv1ParserRuleCall_0; }
		
		//({ExpBinNv0.left=current} OP_ARIT_PRIO_0 right=ExpBinNv1)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{ExpBinNv0.left=current}
		public Action getExpBinNv0LeftAction_1_0() { return cExpBinNv0LeftAction_1_0; }
		
		//OP_ARIT_PRIO_0
		public RuleCall getOP_ARIT_PRIO_0ParserRuleCall_1_1() { return cOP_ARIT_PRIO_0ParserRuleCall_1_1; }
		
		//right=ExpBinNv1
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//ExpBinNv1
		public RuleCall getRightExpBinNv1ParserRuleCall_1_2_0() { return cRightExpBinNv1ParserRuleCall_1_2_0; }
	}
	public class ExpBinNv1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBinNv1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cExpBinLogicalParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpBinNv1LeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_ARIT_PRIO_1ParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightExpBinLogicalParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ExpBinNv1 Expression:
		//	ExpBinLogical ({ExpBinNv1.left=current} OP_ARIT_PRIO_1 right=ExpBinLogical)*
		@Override public ParserRule getRule() { return rule; }
		
		//ExpBinLogical ({ExpBinNv1.left=current} OP_ARIT_PRIO_1 right=ExpBinLogical)*
		public Group getGroup() { return cGroup; }
		
		//ExpBinLogical
		public RuleCall getExpBinLogicalParserRuleCall_0() { return cExpBinLogicalParserRuleCall_0; }
		
		//({ExpBinNv1.left=current} OP_ARIT_PRIO_1 right=ExpBinLogical)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{ExpBinNv1.left=current}
		public Action getExpBinNv1LeftAction_1_0() { return cExpBinNv1LeftAction_1_0; }
		
		//OP_ARIT_PRIO_1
		public RuleCall getOP_ARIT_PRIO_1ParserRuleCall_1_1() { return cOP_ARIT_PRIO_1ParserRuleCall_1_1; }
		
		//right=ExpBinLogical
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//ExpBinLogical
		public RuleCall getRightExpBinLogicalParserRuleCall_1_2_0() { return cRightExpBinLogicalParserRuleCall_1_2_0; }
	}
	public class ExpBinLogicalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpBinLogical");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cExpBinLogicalLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cOP_COMPARISONParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//ExpBinLogical Expression:
		//	Primary ({ExpBinLogical.left=current} OP_COMPARISON right=Primary)*
		@Override public ParserRule getRule() { return rule; }
		
		//Primary ({ExpBinLogical.left=current} OP_COMPARISON right=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({ExpBinLogical.left=current} OP_COMPARISON right=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{ExpBinLogical.left=current}
		public Action getExpBinLogicalLeftAction_1_0() { return cExpBinLogicalLeftAction_1_0; }
		
		//OP_COMPARISON
		public RuleCall getOP_COMPARISONParserRuleCall_1_1() { return cOP_COMPARISONParserRuleCall_1_1; }
		
		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumberLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCallProcExpParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCallVariableParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final RuleCall cExpBinNv0ParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		
		//Primary Expression:
		//	NumberLiteral | CallProcExp | CallVariable |
		//	'(' ExpBinNv0 ')'
		@Override public ParserRule getRule() { return rule; }
		
		//NumberLiteral | CallProcExp | CallVariable | '(' ExpBinNv0 ')'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NumberLiteral
		public RuleCall getNumberLiteralParserRuleCall_0() { return cNumberLiteralParserRuleCall_0; }
		
		//CallProcExp
		public RuleCall getCallProcExpParserRuleCall_1() { return cCallProcExpParserRuleCall_1; }
		
		//CallVariable
		public RuleCall getCallVariableParserRuleCall_2() { return cCallVariableParserRuleCall_2; }
		
		//'(' ExpBinNv0 ')'
		public Group getGroup_3() { return cGroup_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_0() { return cLeftParenthesisKeyword_3_0; }
		
		//ExpBinNv0
		public RuleCall getExpBinNv0ParserRuleCall_3_1() { return cExpBinNv0ParserRuleCall_3_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_2() { return cRightParenthesisKeyword_3_2; }
	}
	public class NumberLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.NumberLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNumberLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final RuleCall cEBigDecimalParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//NumberLiteral:
		//	{NumberLiteral} EBigDecimal;
		@Override public ParserRule getRule() { return rule; }
		
		//{NumberLiteral} EBigDecimal
		public Group getGroup() { return cGroup; }
		
		//{NumberLiteral}
		public Action getNumberLiteralAction_0() { return cNumberLiteralAction_0; }
		
		//EBigDecimal
		public RuleCall getEBigDecimalParserRuleCall_1() { return cEBigDecimalParserRuleCall_1; }
	}
	public class EBigDecimalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBigDecimal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		
		//EBigDecimal ecore::EBigDecimal:
		//	INT | INT '.' INT
		@Override public ParserRule getRule() { return rule; }
		
		//INT | INT '.' INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//INT '.' INT
		public Group getGroup_1() { return cGroup_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_0() { return cINTTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1() { return cFullStopKeyword_1_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_2() { return cINTTerminalRuleCall_1_2; }
	}
	public class ExpNegElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.ExpNeg");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOP_NEGATEParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Assignment cNegateAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNegateExpressionParserRuleCall_1_0 = (RuleCall)cNegateAssignment_1.eContents().get(0);
		
		//ExpNeg:
		//	OP_NEGATE negate=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//OP_NEGATE negate=Expression
		public Group getGroup() { return cGroup; }
		
		//OP_NEGATE
		public RuleCall getOP_NEGATEParserRuleCall_0() { return cOP_NEGATEParserRuleCall_0; }
		
		//negate=Expression
		public Assignment getNegateAssignment_1() { return cNegateAssignment_1; }
		
		//Expression
		public RuleCall getNegateExpressionParserRuleCall_1_0() { return cNegateExpressionParserRuleCall_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class OP_COMPARISONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_COMPARISON");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEqualsSignLessThanSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cEqualsSignEqualsSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cANDKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		private final Keyword cORKeyword_6 = (Keyword)cAlternatives.eContents().get(6);
		private final Keyword cXORKeyword_7 = (Keyword)cAlternatives.eContents().get(7);
		
		////terminal 
		//OP_COMPARISON:
		//	'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR';
		@Override public ParserRule getRule() { return rule; }
		
		//'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'<'
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1() { return cGreaterThanSignKeyword_1; }
		
		//'=<'
		public Keyword getEqualsSignLessThanSignKeyword_2() { return cEqualsSignLessThanSignKeyword_2; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_3() { return cGreaterThanSignEqualsSignKeyword_3; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_4() { return cEqualsSignEqualsSignKeyword_4; }
		
		//'AND'
		public Keyword getANDKeyword_5() { return cANDKeyword_5; }
		
		//'OR'
		public Keyword getORKeyword_6() { return cORKeyword_6; }
		
		//'XOR'
		public Keyword getXORKeyword_7() { return cXORKeyword_7; }
	}
	public class OP_ARIT_PRIO_0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ARIT_PRIO_0");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cPlusSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		////terminal 
		//OP_ARIT_PRIO_0:
		//	'-' | '+';
		@Override public ParserRule getRule() { return rule; }
		
		//'-' | '+'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_1() { return cPlusSignKeyword_1; }
	}
	public class OP_ARIT_PRIO_1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ARIT_PRIO_1");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cAsteriskKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cSolidusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//OP_ARIT_PRIO_1:
		//	'*' | '/';
		@Override public ParserRule getRule() { return rule; }
		
		//'*' | '/'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'*'
		public Keyword getAsteriskKeyword_0() { return cAsteriskKeyword_0; }
		
		//'/'
		public Keyword getSolidusKeyword_1() { return cSolidusKeyword_1; }
	}
	public class OP_ASSIGNMENTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_ASSIGNMENT");
		private final Keyword cHyphenMinusGreaterThanSignKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OP_ASSIGNMENT:
		//	'->';
		@Override public ParserRule getRule() { return rule; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword() { return cHyphenMinusGreaterThanSignKeyword; }
	}
	public class OP_NEGATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Pascalito.OP_NEGATE");
		private final Keyword cHyphenMinusKeyword = (Keyword)rule.eContents().get(1);
		
		////terminal 
		//OP_NEGATE:
		//	'-';
		@Override public ParserRule getRule() { return rule; }
		
		//'-'
		public Keyword getHyphenMinusKeyword() { return cHyphenMinusKeyword; }
	}
	
	
	private final ProgramElements pProgram;
	private final CommandElements pCommand;
	private final ExpressionElements pExpression;
	private final EStringElements pEString;
	private final BlockElements pBlock;
	private final VariableElements pVariable;
	private final ProcedureElements pProcedure;
	private final CallProcElements pCallProc;
	private final AtribuitionElements pAtribuition;
	private final IfElements pIf;
	private final LoopElements pLoop;
	private final CallProcExpElements pCallProcExp;
	private final CallVariableElements pCallVariable;
	private final ExpBinNv0Elements pExpBinNv0;
	private final ExpBinNv1Elements pExpBinNv1;
	private final ExpBinLogicalElements pExpBinLogical;
	private final PrimaryElements pPrimary;
	private final NumberLiteralElements pNumberLiteral;
	private final EBigDecimalElements pEBigDecimal;
	private final ExpNegElements pExpNeg;
	private final EIntElements pEInt;
	private final EBooleanElements pEBoolean;
	private final OP_COMPARISONElements pOP_COMPARISON;
	private final OP_ARIT_PRIO_0Elements pOP_ARIT_PRIO_0;
	private final OP_ARIT_PRIO_1Elements pOP_ARIT_PRIO_1;
	private final OP_ASSIGNMENTElements pOP_ASSIGNMENT;
	private final OP_NEGATEElements pOP_NEGATE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PascalitoGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pCommand = new CommandElements();
		this.pExpression = new ExpressionElements();
		this.pEString = new EStringElements();
		this.pBlock = new BlockElements();
		this.pVariable = new VariableElements();
		this.pProcedure = new ProcedureElements();
		this.pCallProc = new CallProcElements();
		this.pAtribuition = new AtribuitionElements();
		this.pIf = new IfElements();
		this.pLoop = new LoopElements();
		this.pCallProcExp = new CallProcExpElements();
		this.pCallVariable = new CallVariableElements();
		this.pExpBinNv0 = new ExpBinNv0Elements();
		this.pExpBinNv1 = new ExpBinNv1Elements();
		this.pExpBinLogical = new ExpBinLogicalElements();
		this.pPrimary = new PrimaryElements();
		this.pNumberLiteral = new NumberLiteralElements();
		this.pEBigDecimal = new EBigDecimalElements();
		this.pExpNeg = new ExpNegElements();
		this.pEInt = new EIntElements();
		this.pEBoolean = new EBooleanElements();
		this.pOP_COMPARISON = new OP_COMPARISONElements();
		this.pOP_ARIT_PRIO_0 = new OP_ARIT_PRIO_0Elements();
		this.pOP_ARIT_PRIO_1 = new OP_ARIT_PRIO_1Elements();
		this.pOP_ASSIGNMENT = new OP_ASSIGNMENTElements();
		this.pOP_NEGATE = new OP_NEGATEElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Pascalito".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//	'program' Ident=EString
	//	'{'
	//	block=Block
	//	'}';
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Command:
	//	CallProc | Atribuition | If | Loop;
	public CommandElements getCommandAccess() {
		return pCommand;
	}
	
	public ParserRule getCommandRule() {
		return getCommandAccess().getRule();
	}
	
	//Expression:
	//	ExpNeg | ExpBinNv0;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Block:
	//	{Block} ('var' defVariable+=Variable ("," defVariable+=Variable)* ";")* ('procedure' defprocedure+=Procedure)*
	//	'start' execute+=Command* 'end';
	public BlockElements getBlockAccess() {
		return pBlock;
	}
	
	public ParserRule getBlockRule() {
		return getBlockAccess().getRule();
	}
	
	//Variable:
	//	{Variable} name=ID
	//	//		(' -> ' Valor=EString)? - DEFINIR SE VAMOS FAZER ATRIBUI플O NA DEFINI플O.
	//;
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//Procedure:
	//	(name=ID "(" (parameter+=Variable ("," parameter+=Variable)*)? ")")
	//	"{"
	//	block=Block
	//	"}";
	public ProcedureElements getProcedureAccess() {
		return pProcedure;
	}
	
	public ParserRule getProcedureRule() {
		return getProcedureAccess().getRule();
	}
	
	//CallProc:
	//	defined=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')')
	//	';';
	public CallProcElements getCallProcAccess() {
		return pCallProc;
	}
	
	public ParserRule getCallProcRule() {
		return getCallProcAccess().getRule();
	}
	
	//Atribuition:
	//	sets=[Variable] OP_ASSIGNMENT atribuiResultado=Expression ';';
	public AtribuitionElements getAtribuitionAccess() {
		return pAtribuition;
	}
	
	public ParserRule getAtribuitionRule() {
		return getAtribuitionAccess().getRule();
	}
	
	//If:
	//	'if' '(' ifExp=Expression ')'
	//	'{' do+=Command* '}' ('else' '{' elseCmd+=Command* '}')?;
	public IfElements getIfAccess() {
		return pIf;
	}
	
	public ParserRule getIfRule() {
		return getIfAccess().getRule();
	}
	
	//Loop:
	//	'Loop' '(' while=Expression ')'
	//	'{' do+=Command* '}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//CallProcExp:
	//	represent=[Procedure] ('(' (parameter+=Expression ("," parameter+=Expression)*)? ')');
	public CallProcExpElements getCallProcExpAccess() {
		return pCallProcExp;
	}
	
	public ParserRule getCallProcExpRule() {
		return getCallProcExpAccess().getRule();
	}
	
	//CallVariable:
	//	represent=[Variable];
	public CallVariableElements getCallVariableAccess() {
		return pCallVariable;
	}
	
	public ParserRule getCallVariableRule() {
		return getCallVariableAccess().getRule();
	}
	
	//ExpBinNv0 Expression:
	//	ExpBinNv1 ({ExpBinNv0.left=current} OP_ARIT_PRIO_0 right=ExpBinNv1)*
	public ExpBinNv0Elements getExpBinNv0Access() {
		return pExpBinNv0;
	}
	
	public ParserRule getExpBinNv0Rule() {
		return getExpBinNv0Access().getRule();
	}
	
	//ExpBinNv1 Expression:
	//	ExpBinLogical ({ExpBinNv1.left=current} OP_ARIT_PRIO_1 right=ExpBinLogical)*
	public ExpBinNv1Elements getExpBinNv1Access() {
		return pExpBinNv1;
	}
	
	public ParserRule getExpBinNv1Rule() {
		return getExpBinNv1Access().getRule();
	}
	
	//ExpBinLogical Expression:
	//	Primary ({ExpBinLogical.left=current} OP_COMPARISON right=Primary)*
	public ExpBinLogicalElements getExpBinLogicalAccess() {
		return pExpBinLogical;
	}
	
	public ParserRule getExpBinLogicalRule() {
		return getExpBinLogicalAccess().getRule();
	}
	
	//Primary Expression:
	//	NumberLiteral | CallProcExp | CallVariable |
	//	'(' ExpBinNv0 ')'
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//NumberLiteral:
	//	{NumberLiteral} EBigDecimal;
	public NumberLiteralElements getNumberLiteralAccess() {
		return pNumberLiteral;
	}
	
	public ParserRule getNumberLiteralRule() {
		return getNumberLiteralAccess().getRule();
	}
	
	//EBigDecimal ecore::EBigDecimal:
	//	INT | INT '.' INT
	public EBigDecimalElements getEBigDecimalAccess() {
		return pEBigDecimal;
	}
	
	public ParserRule getEBigDecimalRule() {
		return getEBigDecimalAccess().getRule();
	}
	
	//ExpNeg:
	//	OP_NEGATE negate=Expression;
	public ExpNegElements getExpNegAccess() {
		return pExpNeg;
	}
	
	public ParserRule getExpNegRule() {
		return getExpNegAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	////terminal 
	//OP_COMPARISON:
	//	'<' | '>' | '=<' | '>=' | '==' | 'AND' | 'OR' | 'XOR';
	public OP_COMPARISONElements getOP_COMPARISONAccess() {
		return pOP_COMPARISON;
	}
	
	public ParserRule getOP_COMPARISONRule() {
		return getOP_COMPARISONAccess().getRule();
	}
	
	////terminal 
	//OP_ARIT_PRIO_0:
	//	'-' | '+';
	public OP_ARIT_PRIO_0Elements getOP_ARIT_PRIO_0Access() {
		return pOP_ARIT_PRIO_0;
	}
	
	public ParserRule getOP_ARIT_PRIO_0Rule() {
		return getOP_ARIT_PRIO_0Access().getRule();
	}
	
	//OP_ARIT_PRIO_1:
	//	'*' | '/';
	public OP_ARIT_PRIO_1Elements getOP_ARIT_PRIO_1Access() {
		return pOP_ARIT_PRIO_1;
	}
	
	public ParserRule getOP_ARIT_PRIO_1Rule() {
		return getOP_ARIT_PRIO_1Access().getRule();
	}
	
	////terminal 
	//OP_ASSIGNMENT:
	//	'->';
	public OP_ASSIGNMENTElements getOP_ASSIGNMENTAccess() {
		return pOP_ASSIGNMENT;
	}
	
	public ParserRule getOP_ASSIGNMENTRule() {
		return getOP_ASSIGNMENTAccess().getRule();
	}
	
	////terminal 
	//OP_NEGATE:
	//	'-';
	public OP_NEGATEElements getOP_NEGATEAccess() {
		return pOP_NEGATE;
	}
	
	public ParserRule getOP_NEGATERule() {
		return getOP_NEGATEAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
